import test from 'node:test';import assert from 'node:assert/strict';
import {zipSync,strToU8,Zip,ZipDeflate,ZipPassThrough}from'fflate';
import fs from 'node:fs';
import {createDocument} from '../app/editor-core.mjs';
import {readAsepriteExtension,readExtensionAsset,createAsepriteExtensionRegistry,ASEPRITE_EXTENSION_STORAGE_KEY}from'../app/aseprite-extensions.mjs';
import {writePng,writeAseprite}from'../app/formats.mjs';
const enc=s=>strToU8(s),manifest={name:'audit-tools',displayName:'Audit Tools',version:'1.2',author:{name:'Fixture Author'},license:'MIT',contributes:{scripts:[{path:'./tools/paint.lua'}],palettes:[{id:'audit',path:'./colors.gpl'}]}};
const contents={ 'package.json':enc(JSON.stringify(manifest)), 'tools/paint.lua':enc('function init(plugin)\n plugin:newCommand{id="Paint",onclick=function() app.command.Flip() end}\nend'), 'colors.gpl':enc('GIMP Palette\nName: Test\nColumns: 2\n# data\n255 0 0 Red\n0 255 0 Green\n'), 'tools/helper.lua':enc('return 17'), 'README.md':enc('Original fixture; no script is executed.')};
const archive=(files=contents,level=6)=>zipSync(files,{level});
const data=archive();
function changeManifest(patch,extra={}){return archive({...contents,'package.json':enc(JSON.stringify({...manifest,...patch})),...extra});}
function modifyEntries(zip,fn){const out=zip.slice(),v=new DataView(out.buffer);for(let p=0;p<out.length-46;p++)if(v.getUint32(p,true)===0x02014b50)fn(v,p,out);return out;}
function memoryStore(){let data=new Map(),failure=false;return{getSetting:async(k,f)=>structuredClone(data.get(k)??f),setSetting:async(k,v)=>{if(failure)throw Error('quota');data.set(k,structuredClone(v));},fail:()=>{failure=true;},raw:data};}
test('official-style script and GPL package imports metadata/source without running lifecycle',()=>{const p=readAsepriteExtension(data);assert.equal(p.displayName,'Audit Tools');assert.equal(p.contributions[0].status,'source-ready');assert.equal(p.contributions[0].requiresPluginLifecycle,true);assert.match(p.contributions[0].source,/function init/);assert.deepEqual(p.contributions[1].colors,['#ff0000ff','#00ff00ff']);assert.equal(p.manifest.author.name,'Fixture Author');assert.equal(p.assets.length,5);assert.equal(new TextDecoder().decode(readExtensionAsset(p,'tools/helper.lua')),'return 17');});
test('stored ZIP and a single wrapper folder are accepted',()=>{assert.equal(readAsepriteExtension(archive(contents,0)).id,'audit-tools');const wrapped=Object.fromEntries(Object.entries(contents).map(([k,v])=>['download/'+k,v]));assert.equal(readAsepriteExtension(archive(wrapped)).contributions[0].path,'tools/paint.lua');});
test('validated archive data is isolated from caller mutations',()=>{const raw=data.slice(),p=readAsepriteExtension(raw),asset=readExtensionAsset(p,'tools/helper.lua');raw.fill(0);asset.fill(0);assert.equal(new TextDecoder().decode(readExtensionAsset(p,'tools/helper.lua')),'return 17');});
test('unsupported UI themes, languages and novel types remain explicit, with original assets',()=>{const p=readAsepriteExtension(changeManifest({contributes:{themes:[{id:'theme',path:'.'}],languages:[{id:'es',path:'es.ini'}],brushes:[{id:'future',path:'brush.bin'}]}},{'es.ini':enc('[menu]\nfile=Archivo'),'brush.bin':new Uint8Array([1,2])}));assert.equal(p.contributions.length,3);assert.ok(p.contributions.every(c=>c.status==='unsupported'));assert.equal(p.warnings.length,3);assert.deepEqual([...readExtensionAsset(p,'brush.bin')],[1,2]);});
test('PNG palette and dithering images expose exact pixels; key definitions are data only',()=>{const png=writePng(2,1,new Uint8Array([255,0,0,255,0,0,0,0]));const p=readAsepriteExtension(changeManifest({contributes:{palettes:[{id:'png',path:'colors.png'}],ditheringMatrices:[{id:'dither',path:'matrix.png'}],keys:[{id:'keys',path:'shortcuts.aseprite-keys'}]}},{'colors.png':png,'matrix.png':png,'shortcuts.aseprite-keys':enc('<keyboard version="1"><commands><key command="Undo" shortcut="Ctrl+Z" /></commands></keyboard>')}));assert.deepEqual(p.contributions[0].colors,['#00000000','#ff0000ff']);assert.deepEqual(p.contributions[1].image.pixels,[255,0,0,255,0,0,0,0]);assert.equal(p.contributions[1].status,'data-only');assert.equal(p.contributions[2].status,'data-only');});
test('unsupported palette files are preserved with an explicit diagnostic',()=>{const p=readAsepriteExtension(changeManifest({contributes:{palettes:[{id:'aco',path:'colors.aco'}]}},{'colors.aco':new Uint8Array([0,1])}));assert.equal(p.contributions[0].status,'unsupported');assert.match(p.contributions[0].reason,/cannot be applied/);});
for(const path of['../escape.lua','/absolute.lua','C:/drive.lua','tools\\escape.lua','nested/../escape.lua','nested//escape.lua','__x/CON.txt','nested/evil.'])test(`reject unsafe ZIP path ${path}`,()=>assert.throws(()=>readAsepriteExtension(archive({...contents,[path]:enc('bad')})),/unsafe path/));
test('manifest contribution cannot escape the package',()=>assert.throws(()=>readAsepriteExtension(changeManifest({contributes:{scripts:[{path:'../outside.lua'}]}})),/unsafe path/));
test('duplicate canonical ZIP paths and file/directory conflicts are rejected',()=>{assert.throws(()=>readAsepriteExtension(archive({...contents,'COLORS.GPL':contents['colors.gpl']})),/duplicate/);assert.throws(()=>readAsepriteExtension(archive({...contents,tools:enc('file')})),/conflicts with a directory/);});
test('missing referenced files and multiple package manifests fail',()=>{assert.throws(()=>readAsepriteExtension(changeManifest({contributes:{scripts:[{path:'missing.lua'}]}})),/Missing scripts/);assert.throws(()=>readAsepriteExtension(archive({'a/package.json':contents['package.json'],'b/package.json':contents['package.json']})),/one package.json/);});
test('Lua bytecode, malformed UTF-8, external shortcut declarations and oversized scripts fail',()=>{assert.throws(()=>readAsepriteExtension(archive({...contents,'tools/paint.lua':new Uint8Array([27,76,117,97,0])})),/bytecode/);assert.throws(()=>readAsepriteExtension(archive({...contents,'tools/paint.lua':new Uint8Array([255])})),/UTF-8/);assert.throws(()=>readAsepriteExtension(archive({...contents,'tools/paint.lua':new Uint8Array(1024*1024+1).fill(32)})),/1 MB/);assert.throws(()=>readAsepriteExtension(changeManifest({contributes:{keys:[{path:'keys.xml'}]}},{'keys.xml':enc('<!DOCTYPE keyboard SYSTEM "file:///x"><keyboard/>')})),/external declarations/);});
test('CRC corruption and local/central header mismatch fail',()=>{const stored=archive(contents,0),v=new DataView(stored.buffer),start=30+v.getUint16(26,true)+v.getUint16(28,true);stored[start]^=1;assert.throws(()=>readAsepriteExtension(stored),/checksum/);const mismatch=data.slice();new DataView(mismatch.buffer).setUint16(8,99,true);assert.throws(()=>readAsepriteExtension(mismatch),/headers disagree/);});
test('ZIP symlinks, encryption, unsupported compression, huge declarations fail before extraction',()=>{
 assert.throws(()=>readAsepriteExtension(modifyEntries(data,(v,p)=>{v.setUint16(p+4,0x0314,true);v.setUint32(p+38,0xa1ff0000,true);})),/links/);
 assert.throws(()=>readAsepriteExtension(modifyEntries(data,(v,p)=>v.setUint16(p+8,1,true))),/Encrypted/);
 assert.throws(()=>readAsepriteExtension(modifyEntries(data,(v,p)=>v.setUint16(p+10,99,true))),/stored or deflated/);
 assert.throws(()=>readAsepriteExtension(modifyEntries(data,(v,p)=>v.setUint32(p+24,9*1024*1024,true))),/file limit/);
});
test('declared-small DEFLATE expansion aborts before copying a larger payload',()=>{const packed=archive({'package.json':contents['package.json'],'bomb.txt':new Uint8Array(2*1024*1024).fill(65)});const changed=modifyEntries(packed,(v,p,out)=>{const n=v.getUint16(p+28,true),name=new TextDecoder().decode(out.subarray(p+46,p+46+n));if(name==='bomb.txt'){v.setUint32(p+24,10,true);v.setUint32(v.getUint32(p+42,true)+22,10,true);}});assert.throws(()=>readAsepriteExtension(changed),/exceeds its declared size/);});
test('install/get/reload/disable/replace/remove persist raw packages without execution',async()=>{const store=memoryStore();let time=10;const registry=createAsepriteExtensionRegistry(store,{now:()=>time});const p=await registry.install(data);assert.equal(p.installedAt,10);assert.ok(readExtensionAsset(p,'tools/helper.lua').length);assert.equal((await registry.list()).length,1);await assert.rejects(()=>registry.install(data),/already exists/);await registry.setEnabled('audit-tools',false);time=20;await registry.install(changeManifest({version:'2.0'}),{replace:true});const reloaded=createAsepriteExtensionRegistry(store),fresh=await reloaded.get('audit-tools');assert.equal(fresh.version,'2.0');assert.equal(fresh.enabled,false);assert.equal(fresh.installedAt,10);assert.equal(fresh.updatedAt,20);assert.ok(readExtensionAsset(fresh,'tools/paint.lua').length);assert.equal(await reloaded.remove('audit-tools'),true);assert.equal(await reloaded.remove('audit-tools'),false);assert.equal(await reloaded.get('audit-tools'),null);});
test('queued concurrent installs retain both packages; failed storage preserves prior archive',async()=>{const store=memoryStore(),r=createAsepriteExtensionRegistry(store);await Promise.all([r.install(data),r.install(changeManifest({name:'second'}))]);assert.equal((await r.list()).length,2);store.fail();await assert.rejects(()=>r.remove('audit-tools'),/quota/);assert.equal((await r.list()).length,2);});
test('corrupt saved registry is surfaced and never silently overwritten',async()=>{const store=memoryStore();store.raw.set(ASEPRITE_EXTENSION_STORAGE_KEY,{version:999,packages:[]});const r=createAsepriteExtensionRegistry(store);await assert.rejects(()=>r.list(),/registry is invalid/);await assert.rejects(()=>r.install(data),/registry is invalid/);assert.equal(store.raw.get(ASEPRITE_EXTENSION_STORAGE_KEY).version,999);});

test('streaming ZIP data descriptors are accepted for stored and deflated entries',()=>{for(const Stream of[ZipDeflate,ZipPassThrough]){const chunks=[];const zip=new Zip((error,chunk)=>{if(error)throw error;chunks.push(chunk);});for(const[name,data]of Object.entries(contents)){const entry=new Stream(name);zip.add(entry);entry.push(data,true);}zip.end();const all=new Uint8Array(chunks.reduce((n,c)=>n+c.length,0));let p=0;for(const c of chunks){all.set(c,p);p+=c.length;}assert.equal(readAsepriteExtension(all).id,'audit-tools');}});
test('native palette chunks are usable without decoding or rendering sprite artwork',()=>{const document=createDocument({width:1,height:1,palette:['#12345678','#abcdef99','#00000000']}),native=writeAseprite(document),p=readAsepriteExtension(changeManifest({contributes:{palettes:[{id:'native',path:'palette.aseprite'}]}},{'palette.aseprite':native}));assert.deepEqual(p.contributions[0].colors,document.palette);});
test('truecolor PNG palette ordering matches an independently captured Aseprite oracle',()=>{const vector=JSON.parse(fs.readFileSync(new URL('./fixtures/aseprite-extensions/png-palette-oracle.json',import.meta.url))),png=writePng(vector.input.length,1,Uint8Array.from(vector.input.flat())),p=readAsepriteExtension(changeManifest({contributes:{palettes:[{id:'oracle',path:'palette.png'}]}},{'palette.png':png}));const hex=c=>'#'+c.map(v=>v.toString(16).padStart(2,'0')).join('');assert.deepEqual(p.contributions[0].colors,vector.output.map(hex));});
test('indexed PNG palette preserves original indices, unused entries and transparent RGB',()=>{const png=fs.readFileSync(new URL('./fixtures/aseprite-extensions/indexed-palette.png',import.meta.url)),p=readAsepriteExtension(changeManifest({contributes:{palettes:[{id:'indexed',path:'palette.png'}]}},{'palette.png':png}));assert.deepEqual(p.contributions[0].colors,['#ff000000','#0000ffff','#00ff00ff','#808080ff']);});
test('PNG palettes needing quantization report the limit instead of dropping colors',()=>{const png=writePng(300,1,Uint8Array.from(Array.from({length:300},(_,i)=>[i%256,Math.floor(i/256)*127,(i*17)%256,255]).flat())),p=readAsepriteExtension(changeManifest({contributes:{palettes:[{id:'large',path:'palette.png'}]}},{'palette.png':png}));assert.equal(p.contributions[0].status,'unsupported');assert.match(p.contributions[0].reason,/quantization/);});
test('future contribution metadata without a file path is explicitly retained',()=>{const p=readAsepriteExtension(changeManifest({contributes:{futureCommands:[{id:'future',settings:{a:1}}]}}));assert.equal(p.contributions[0].status,'unsupported');assert.deepEqual(p.contributions[0].metadata.settings,{a:1});});
test('manifest nesting and malformed JASC palette counts have explicit diagnostics',()=>{let value={};for(let i=0;i<40;i++)value={next:value};assert.throws(()=>readAsepriteExtension(changeManifest({extra:value})),/nesting/);const p=readAsepriteExtension(changeManifest({contributes:{palettes:[{id:'jasc',path:'colors.pal'}]}},{'colors.pal':enc('JASC-PAL\n0100\n5\n255 0 0\n')}));assert.equal(p.contributions[0].status,'unsupported');assert.match(p.contributions[0].reason,/color count/);});
