import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,copyFile,symlink,rm,access,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {readPng,readAseprite,readBmp,readTga} from '../app/formats.mjs';
import {extractLicenseToken} from '../app/cli.mjs';
const exec=promisify(execFile),here=join(dirname(fileURLToPath(import.meta.url)),'../app'),cli=join(here,'cli.mjs');
async function run(args,entry=cli,env={}){return exec(process.execPath,[entry,...args],{env:{...process.env,PIXELWALL_PRO_LICENSE:'',...env},maxBuffer:8*1024*1024});}
async function temp(t){const dir=await mkdtemp(join(tmpdir(),'pixelwall-cli-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));return dir;}
test('offline CLI creates, edits, scripts, renders, inspects and round-trips a native project',async t=>{const dir=await temp(t),project=join(dir,'hero.pixelwall'),edited=join(dir,'edited.pixelwall'),png=join(dir,'hero.png'),ase=join(dir,'hero.aseprite'),scripted=join(dir,'scripted.pixelwall');await run(['new','--width','4','--height','4','--out',project]);const commands=join(dir,'edits.json');await writeFile(commands,JSON.stringify([{type:'draw.stroke',points:[{x:1,y:1}],color:'#ff0000ff',size:1}]));await run(['apply',project,'--commands',commands,'--out',edited]);await run(['render',edited,'--scale','2','--out',png]);const image=readPng(await readFile(png));assert.equal(image.width,8);assert.deepEqual(image.rgba.slice((2*8+2)*4,(2*8+2)*4+4),Uint8Array.of(255,0,0,255));const {stdout}=await run(['inspect',edited]);assert.equal(JSON.parse(stdout).images,1);await run(['export',edited,'--format','aseprite','--out',ase]);assert.equal(readAseprite(await readFile(ase)).document.width,4);for(const format of ['bmp','tga']){const imagePath=join(dir,`hero.${format}`);await run(['export',edited,'--format',format,'--out',imagePath]);const decoded=(format==='bmp'?readBmp:readTga)(await readFile(imagePath));assert.deepEqual(decoded.rgba.slice((1*4+1)*4,(1*4+1)*4+4),Uint8Array.of(255,0,0,255));}const script=join(dir,'draw.mjs');await writeFile(script,"export default ({apply})=>{apply({type:'document.update',patch:{name:'Scripted hero'}});};\n");await run(['script',edited,'--script',script,'--out',scripted]);assert.equal(JSON.parse(await readFile(scripted,'utf8')).name,'Scripted hero');const catalog=JSON.parse((await run(['commands'])).stdout);assert.ok(catalog.some(c=>c.type==='animation.particles'));});
test('every paid CLI export rejects missing and forged proof without creating output',async t=>{const dir=await temp(t),project=join(dir,'input.pixelwall');await run(['new','--width','2','--out',project]);for(const format of ['gif','sheet','atlas','zip']){const out=join(dir,`blocked.${format}`);await assert.rejects(run(['export',project,'--format',format,'--out',out]),e=>e.stderr.includes('valid PixelWall Pro license'));await assert.rejects(access(out));await assert.rejects(run(['export',project,'--format',format,'--out',out],cli,{PIXELWALL_PRO_LICENSE:'PW2.fake.forged'}),e=>e.stderr.includes('valid PixelWall Pro license'));await assert.rejects(access(out));}});
test('signed license unlocks all paid exports offline in a release with the matching pinned public key',async t=>{const dir=await temp(t);for(const name of (await readdir(here)).filter(name=>name.endsWith('.mjs')))await copyFile(join(here,name),join(dir,name));await symlink(join(here,'../node_modules'),join(dir,'node_modules'),'dir');const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),publicKey=await crypto.subtle.exportKey('jwk',pair.publicKey),claims={version:2,product:'pixelwall-pro',mode:'live',purchaseId:'cs_live_testfixture12345',issuedAt:1,perpetual:true,keyId:'fixture'},payload=Buffer.from(JSON.stringify(claims)).toString('base64url'),signature=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},pair.privateKey,new TextEncoder().encode(`PW2.${payload}`)),token=`PW2.${payload}.${Buffer.from(signature).toString('base64url')}`;await writeFile(join(dir,'license-public-keys.mjs'),`export const PINNED_PUBLIC_KEYS=${JSON.stringify({fixture:publicKey})};`);const entry=join(dir,'cli.mjs'),project=join(dir,'input.pixelwall');await run(['new','--width','2','--out',project],entry);const licensePath=join(dir,'pixelwall-pro-license.txt');await writeFile(licensePath,`PixelWall Pro — perpetual ownership license\n\n${token}\n\nKeep this file private. Anyone with this code can use your Pro access. PW2 ownership licenses work offline in a downloaded or installed PixelWall build; PW1 codes need one online conversion.\nTo restore: open PixelWall, choose Pro, then Restore Pro.\nStore: https://pixelwall.example\nMode: live\nSupport: contact@caplock.ai\nThis code restores Pro access, not your artwork. Use Save Project to back up artwork.\n`);const expected={gif:'GIF89a',sheet:'PNG',atlas:'PNG',zip:'PK'};for(const format of Object.keys(expected)){const out=join(dir,`export.${format==='atlas'||format==='sheet'?'png':format}`);await run(['export',project,'--format',format,'--out',out,...(format==='gif'?['--license',licensePath]:[])],entry,format==='gif'?{}:{PIXELWALL_PRO_LICENSE:token});const data=await readFile(out);assert.ok(data.length>20);if(format==='sheet'||format==='atlas')assert.equal(readPng(data).width>=2,true);else assert.equal(data.toString('ascii',0,format==='gif'?6:2),expected[format]);}});

test('license-file parsing rejects missing, oversized, malformed and ambiguous PW2 codes',()=>{assert.throws(()=>extractLicenseToken('PW1.old.code'),/does not contain/);assert.throws(()=>extractLicenseToken('PW2.bad.malformed'),/malformed/);const token='PW2.abc.'+'A'.repeat(86);assert.equal(extractLicenseToken('Heading\n'+token+'\nInstructions'),token);assert.throws(()=>extractLicenseToken(token+'\n'+token),/multiple/);assert.throws(()=>extractLicenseToken('x'.repeat(65537)),/64 KiB/);});
