import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {isStableVersion,compareVersions,validateManifest,fetchManifest,createUpdateController,createFileSettingsStore,createDesktopMenuTemplate,UPDATE_FEED_URL,CHECK_INTERVAL_MS,STARTUP_DELAY_MS,SUPPORTED_TARGETS} from '../desktop/update-checker.mjs';
const origin='https://www.pixelwall.dev';
function manifest(version='0.3.0') {return {schemaVersion:1,version,releaseNotesUrl:`${origin}/downloads#release-${version.replaceAll('.','-')}`,releaseNotes:['Improved drawing tools.'],downloads:Object.fromEntries(SUPPORTED_TARGETS.map(target=>{const suffix={'darwin-arm64':'mac-arm64.zip','darwin-x64':'mac-x64.zip','win32-x64':'windows-x64.exe','linux-x64':'linux-x64.AppImage'}[target];const filename=`PixelWall-${version}-${suffix}`;return [target,{url:`${origin}/downloads/desktop/${version}/${filename}`,filename,sha256:'a'.repeat(64),size:1024}];}))};}
function response(body=JSON.stringify(manifest()),options={}) {const result=new Response(body,{status:options.status??200,headers:{'content-type':'application/json',...options.headers}});Object.defineProperty(result,'url',{value:options.url??UPDATE_FEED_URL});Object.defineProperty(result,'redirected',{value:options.redirected??false});return result;}
function harness(overrides={}) {const notices=[],opened=[],saved=[];const controller=createUpdateController({currentVersion:'0.2.0',platform:'darwin',arch:'arm64',packaged:false,fetch:async()=>response(),notify:async event=>{notices.push(event);return 'later';},openExternal:async url=>opened.push(url),writeSettings:async settings=>saved.push(settings),...overrides});return {controller,notices,opened,saved};}
function timerHarness() {let now=1_000_000;const tasks=new Map();let id=0;return {now:()=>now,advance:value=>{now+=value;},tasks,timers:{setTimeout(fn,delay){tasks.set(++id,{fn,delay});return id;},clearTimeout(key){tasks.delete(key);}}};}

test('strict stable versions compare numerically without integer overflow',()=>{assert.equal(compareVersions('0.10.0','0.2.0'),1);assert.equal(compareVersions('2.0.0','10.0.0'),-1);assert.equal(compareVersions('0.2.0','0.2.0'),0);assert.equal(compareVersions('9999999999999999.0.0','9999999999999998.9.9'),1);for(const value of ['01.0.0','1.02.0','1.0.0-beta','1.0.0+test','v1.0.0','1.0',' 1.0.0'])assert.equal(isStableVersion(value),false);});
test('manifest preserves approved download metadata and exact notes anchor',()=>{const result=validateManifest(manifest());assert.equal(result.releaseNotesUrl,origin+'/downloads#release-0-3-0');assert.equal(Object.keys(result.downloads).length,4);assert.equal(Object.isFrozen(result.downloads['darwin-arm64']),true);});
for(const [name,change]of [
 ['schema',value=>value.schemaVersion=2],['prerelease',value=>value.version='0.3.0-beta'],['other notes origin',value=>value.releaseNotesUrl='https://private.example/downloads#release-0-3-0'],['wrong notes anchor',value=>value.releaseNotesUrl=origin+'/downloads#release-0-2-0'],['download redirect location',value=>value.downloads['darwin-arm64'].url='https://evil.example/file.zip'],['download query',value=>value.downloads['darwin-arm64'].url+='?redirect=elsewhere'],['encoded filename',value=>value.downloads['darwin-arm64'].url=value.downloads['darwin-arm64'].url.replace('PixelWall','%50ixelWall')],['parent path',value=>value.downloads['darwin-arm64'].filename='../PixelWall.zip'],['checksum',value=>value.downloads['darwin-arm64'].sha256='bad'],['size',value=>value.downloads['darwin-arm64'].size=-1],['notes size',value=>value.releaseNotes=['x'.repeat(1001)]]
])test(`rejects invalid manifest ${name}`,()=>{const value=manifest();change(value);assert.throws(()=>validateManifest(value));});
test('fetch uses only pinned feed without credentials or redirects',async()=>{await fetchManifest(async(url,options)=>{assert.equal(url,UPDATE_FEED_URL);assert.equal(options.redirect,'error');assert.equal(options.credentials,'omit');assert.equal(options.cache,'no-store');return response();});});
for(const [name,options]of [['redirect flag',{redirected:true}],['wrong response URL',{url:'https://private.example/latest.json'}],['HTML response',{headers:{'content-type':'text/html'}}],['HTTP error',{status:503}],['oversized header',{headers:{'content-length':'65537'}}]])test(`rejects feed ${name}`,async()=>assert.rejects(fetchManifest(async()=>response(undefined,options))));
test('limits streamed bytes when no length header is present',async()=>{let cancelled=false;const body=new ReadableStream({start(controller){controller.enqueue(new Uint8Array(100));},cancel(){cancelled=true;}});await assert.rejects(fetchManifest(async()=>response(body),{maxBytes:64}),/size limit/);assert.equal(cancelled,true);});
test('timeout rejects a stalled fetch and aborts the request',async()=>{let signal;await assert.rejects(fetchManifest(async(_url,options)=>{signal=options.signal;return new Promise(()=>{});},{timeoutMs:15}),/timed out/);assert.equal(signal.aborted,true);});
test('automatic current and offline checks stay silent; manual checks respond',async()=>{const up=harness({fetch:async()=>response(JSON.stringify(manifest('0.2.0')))});await up.controller.check();assert.equal(up.notices.length,0);await up.controller.check({manual:true});assert.equal(up.notices[0].kind,'current');const offline=harness({fetch:async()=>{throw Error('offline');}});await offline.controller.check();assert.equal(offline.notices.length,0);await offline.controller.check({manual:true});assert.equal(offline.notices[0].kind,'error');});
test('background releases notify once across restarts and manual check can repeat',async()=>{let settings={};const first=harness({readSettings:async()=>settings,writeSettings:async value=>settings=value});await first.controller.check();assert.equal(first.notices.length,1);await first.controller.check();assert.equal(first.notices.length,1);const restarted=harness({readSettings:async()=>settings});await restarted.controller.check();assert.equal(restarted.notices.length,0);await restarted.controller.check({manual:true});assert.equal(restarted.notices.length,1);assert.equal(settings.notifiedVersion,'0.3.0');});
test('only explicit Download or Release notes actions open validated URLs',async()=>{for(const action of ['download','notes','later']){const notices=[],run=harness({notify:async event=>{notices.push(event);return action;}});await run.controller.check();assert.equal(notices[0].kind,'available');assert.deepEqual(run.opened,action==='download'?[manifest().downloads['darwin-arm64'].url]:action==='notes'?[manifest().releaseNotesUrl]:[]);}});
test('concurrent manual check joins background request and receives status',async()=>{let complete,calls=0;const run=harness({fetch:async()=>{calls++;return new Promise(resolve=>complete=resolve);}});const background=run.controller.check();const manual=run.controller.check({manual:true});assert.equal(background,manual);await new Promise(resolve=>setImmediate(resolve));complete(response(JSON.stringify(manifest('0.2.0'))));await manual;assert.equal(calls,1);assert.equal(run.notices.length,1);assert.equal(run.notices[0].kind,'current');});
test('selects correct platform download for each supported target',async()=>{for(const target of SUPPORTED_TARGETS){const [platform,arch]=target.split('-');const run=harness({platform,arch,notify:async()=> 'download'});await run.controller.check();assert.deepEqual(run.opened,[manifest().downloads[target].url]);}});
test('unsupported platform and missing target are graceful',async()=>{let fetched=false;const run=harness({platform:'linux',arch:'arm64',fetch:async()=>{fetched=true;return response();}});await run.controller.check();assert.equal(run.notices.length,0);await run.controller.check({manual:true});assert.equal(run.notices[0].kind,'unsupported');assert.equal(fetched,false);const value=manifest();delete value.downloads['darwin-arm64'];const missing=harness({fetch:async()=>response(JSON.stringify(value))});await missing.controller.check({manual:true});assert.equal(missing.notices[0].kind,'unsupported');});
test('packaged startup delays checks and reschedules exactly 24h after each attempt',async()=>{const clock=timerHarness(),run=harness({packaged:true,...clock});await run.controller.start();assert.equal(clock.tasks.size,1);const [id,task]=[...clock.tasks][0];assert.equal(task.delay,STARTUP_DELAY_MS);clock.tasks.delete(id);clock.advance(task.delay);task.fn();await new Promise(resolve=>setImmediate(resolve));assert.equal(run.notices.length,1);assert.equal([...clock.tasks.values()][0].delay,CHECK_INTERVAL_MS);run.controller.dispose();assert.equal(clock.tasks.size,0);});
test('stored recent check waits only until due; disabling automatic checks persists',async()=>{const clock=timerHarness(),run=harness({packaged:true,...clock,readSettings:async()=>({lastCheckedAt:clock.now()-5000})});await run.controller.start();assert.equal([...clock.tasks.values()][0].delay,CHECK_INTERVAL_MS-5000);await run.controller.setAutomaticChecks(false);assert.equal(clock.tasks.size,0);assert.equal(run.saved.at(-1).automaticChecks,false);});
test('development builds and disabled preferences never schedule background checks',async()=>{for(const options of [{packaged:false},{packaged:true,readSettings:async()=>({automaticChecks:false})}]){const clock=timerHarness(),run=harness({...clock,...options});await run.controller.start();assert.equal(clock.tasks.size,0);}});
test('dispose aborts running network check without a late notification',async()=>{let began;const running=new Promise(resolve=>began=resolve);const run=harness({fetch:async(_url,{signal})=>new Promise((_,reject)=>{began();signal.addEventListener('abort',()=>reject(Error('aborted')),{once:true});})});const check=run.controller.check({manual:true});await running;run.controller.dispose();assert.equal((await check).status,'stopped');assert.equal(run.notices.length,0);});
test('settings file persists preferences atomically without artwork fields',async t=>{const root=await mkdtemp(join(tmpdir(),'pixelwall-update-settings-'));t.after(()=>rm(root,{recursive:true,force:true}));const file=join(root,'update-checker.json'),store=createFileSettingsStore(file);assert.deepEqual(await store.readSettings(),{});await Promise.all([store.writeSettings({automaticChecks:true,notifiedVersion:'0.3.0',artwork:'DO NOT WRITE'}),store.writeSettings({automaticChecks:false,notifiedVersion:'0.4.0',lastCheckedAt:123})]);const saved=await store.readSettings();assert.equal(saved.automaticChecks,false);assert.equal(saved.notifiedVersion,'0.4.0');assert.doesNotMatch(await readFile(file,'utf8'),/artwork|DO NOT WRITE/);assert.deepEqual(await readdir(root),['update-checker.json']);await writeFile(file,'not json');assert.deepEqual(await store.readSettings(),{});});
test('native menus retain standard roles and expose update actions on every OS',()=>{for(const platform of ['darwin','win32','linux']){let checked=false,toggled;const menu=createDesktopMenuTemplate({platform,automaticChecks:true,packaged:true,onCheck:()=>checked=true,onToggle:value=>toggled=value,onDocumentation(){}});for(const role of ['fileMenu','editMenu','viewMenu','windowMenu','help'])assert.ok(menu.some(item=>item.role===role));const items=menu.flatMap(item=>item.submenu??[]),check=items.find(item=>item.label==='Check for Updates…'),toggle=items.find(item=>item.type==='checkbox');assert.ok(check);check.click();toggle.click({checked:false});assert.equal(checked,true);assert.equal(toggled,false);assert.equal(toggle.enabled,true);}});

test('rejects a different platform artifact or version under a valid download key',()=>{const swapped=manifest();swapped.downloads['darwin-arm64']={...swapped.downloads['win32-x64']};assert.throws(()=>validateManifest(swapped),/platform and version/);const stale=manifest();stale.downloads['darwin-arm64'].filename='PixelWall-0.2.0-mac-arm64.zip';stale.downloads['darwin-arm64'].url=origin+'/downloads/desktop/0.3.0/PixelWall-0.2.0-mac-arm64.zip';assert.throws(()=>validateManifest(stale),/platform and version/);});
test('future unsupported targets remain harmless alongside known downloads',()=>{const value=manifest();value.downloads['win32-arm64']={filename:'PixelWall-0.3.0-windows-arm64.exe',url:origin+'/downloads/desktop/0.3.0/PixelWall-0.3.0-windows-arm64.exe'};assert.ok(validateManifest(value).downloads['win32-arm64']);assert.equal(SUPPORTED_TARGETS.includes('win32-arm64'),false);});
test('turning automatic checks off suppresses a pending background notification',async()=>{let complete,began;const waiting=new Promise(resolve=>began=resolve);const run=harness({fetch:async()=>{began();return new Promise(resolve=>complete=resolve);}});const checking=run.controller.check();await waiting;await run.controller.setAutomaticChecks(false);complete(response());assert.equal((await checking).status,'disabled');assert.equal(run.notices.length,0);});
