import test from 'node:test';
import assert from 'node:assert/strict';
import {readBmp,writeBmp,readTga,writeTga,packAtlas,makeGamePackage,readPng,readAseprite,writeAseprite,importSheet} from '../app/formats.mjs';
import {createDocument,applyCommand,renderFrame} from '../app/editor-core.mjs';
import {unzipSync} from 'fflate';
const colors=Uint8Array.of(255,0,0,255,0,255,0,128,0,0,255,0,255,255,255,255);
const word=n=>[n&255,n>>>8&255],dword=n=>[...word(n),...word(n>>>16)],json=b=>JSON.parse(new TextDecoder().decode(b));
test('BMP v5 preserves RGBA, emits explicit masks and rejects truncated raster',()=>{const b=writeBmp(2,2,colors),v=new DataView(b.buffer);assert.equal(v.getUint32(14,true),124);assert.equal(v.getUint32(54,true),0xff0000);assert.equal(v.getUint32(66,true),0xff000000);assert.deepEqual(readBmp(b).rgba,colors);assert.throws(()=>readBmp(b.slice(0,-1)),/Truncated/);});
test('BMP reads an independently assembled bottom-up 24-bit image',()=>{const header=[66,77,...dword(62),0,0,0,0,...dword(54),...dword(40),...dword(1),...dword(2),...word(1),...word(24),...new Array(24).fill(0)],b=Uint8Array.from([...header,255,0,0,0,0,0,255,0]);assert.deepEqual(readBmp(b).rgba,Uint8Array.of(255,0,0,255,0,0,255,255));});
test('BMP reads indexed RLE8 data including explicit end-of-bitmap',()=>{const pixels=[2,1,0,0,2,0,0,1],header=[66,77,...dword(62+pixels.length),0,0,0,0,...dword(62),...dword(40),...dword(2),...dword(2),...word(1),...word(8),...dword(1),...dword(pixels.length),...dword(0),...dword(0),...dword(2),...dword(0)],b=Uint8Array.from([...header,0,0,255,0,0,255,0,0,...pixels]);assert.deepEqual(readBmp(b).rgba,Uint8Array.of(255,0,0,255,255,0,0,255,0,255,0,255,0,255,0,255));});
test('TGA raw and RLE outputs retain straight alpha and pixel orientation',()=>{for(const rle of [false,true]){const b=writeTga(2,2,colors,{rle}),result=readTga(b);assert.deepEqual(result.rgba,colors);assert.deepEqual(result.warnings,[]);assert.equal(b[2],rle?10:2);}});
test('TGA independently assembled indexed and bottom-up RLE files decode',()=>{const indexed=Uint8Array.from([0,1,1,...word(3),...word(2),24,0,0,0,0,...word(2),...word(1),8,32,0,0,255,0,255,0,3,4]);assert.deepEqual(readTga(indexed).rgba,Uint8Array.of(255,0,0,255,0,255,0,255));const rle=Uint8Array.from([0,0,10,0,0,0,0,0,0,0,0,0,...word(2),...word(1),24,0,129,255,0,0]);assert.deepEqual(readTga(rle).rgba,Uint8Array.of(0,0,255,255,0,0,255,255));assert.throws(()=>readTga(rle.slice(0,-1)),/Truncated/);});
test('atlas horizontal, vertical and grid layouts honor their controls',()=>{const entries=Array.from({length:3},(_,i)=>({name:`f${i}`,width:1,height:1,rgba:Uint8Array.of(255,0,0,255)}));const h=packAtlas(entries,{layout:'horizontal',padding:0,border:0,trim:false}),v=packAtlas(entries,{layout:'vertical',padding:0,border:0}),g=packAtlas(entries,{layout:'grid',columns:2,padding:0,border:0});assert.deepEqual([h.width,h.height],[3,1]);assert.deepEqual([v.width,v.height],[1,3]);assert.deepEqual([g.width,g.height],[2,2]);const sheet={width:3,height:1,rgba:Uint8Array.of(0,0,0,0,255,0,0,255,0,0,0,0)};assert.equal(importSheet(sheet,{frameWidth:1,frameHeight:1,padding:0,columns:1}).frames.length,1);});
function tiledRender(files,map){const out=new Uint8Array(map.width*map.tilewidth*map.height*map.tileheight*4),width=map.width*map.tilewidth;for(const layer of map.layers){for(let i=0;i<layer.data.length;i++){const value=layer.data[i]>>>0,gid=value&0x0fffffff;if(!gid)continue;const setRef=[...map.tilesets].reverse().find(t=>t.firstgid<=gid),setPath=setRef.source.replace(/^\.\.\//,''),ts=json(files[setPath]),tile=ts.tiles.find(t=>t.id===gid-setRef.firstgid),folder=setPath.slice(0,setPath.lastIndexOf('/')+1),image=readPng(files[folder+tile.image]);for(let y=0;y<map.tileheight;y++)for(let x=0;x<map.tilewidth;x++){let u=x,v=y;if(value&0x80000000)u=image.width-1-u;if(value&0x40000000)v=image.height-1-v;if(value&0x20000000)[u,v]=[v,u];const p=(v*image.width+u)*4,d=((Math.floor(i/map.width)*map.tileheight+y)*width+(i%map.width)*map.tilewidth+x)*4;out.set(image.rgba.subarray(p,p+4),d);}}}return out;}
test('game ZIP includes actual tiles and Tiled maps whose rotations match the engine',()=>{for(const rotation of [0,90,180,270])for(const flipX of [false,true])for(const flipY of [false,true]){let d=createDocument({name:'Game',width:2,height:2});d=applyCommand(d,{type:'tileset.add',tileset:{id:'ts',name:'Terrain',tileWidth:2,tileHeight:2,tiles:[{id:'tile',pixels:['#ff0000ff','#00ff00ff','#0000ffff','#ffffffff']}]}});d=applyCommand(d,{type:'layer.add',layer:{id:'tiles',name:'Ground',type:'tilemap'}});d=applyCommand(d,{type:'tilemap.paint',layerId:'tiles',tilesetId:'ts',columns:1,rows:1,points:[{x:0,y:0,tileId:'tile',rotate:rotation,flipX,flipY}]});for(const doc of [d,readAseprite(writeAseprite(d)).document]){const files=unzipSync(makeGamePackage(doc)),manifest=json(files['manifest.json']);assert.ok(files['sprites.png']);assert.ok(files['Game.pixelwall']||Object.keys(files).some(k=>k.endsWith('.pixelwall')));assert.ok(Object.keys(files).some(k=>/tile-0000\.png$/.test(k)));const map=json(files[manifest.maps[0].source]);assert.deepEqual(tiledRender(files,map),new Uint8Array(renderFrame(doc)),`Tiled rotation ${rotation}, x${flipX}, y${flipY}`);}}});
test('game ZIP creates distinct tile PNG palettes for indexed animation frames',()=>{let d=createDocument({name:'Indexed',width:1,height:1,colorMode:'indexed',palette:['#ff0000ff','#00ff00ff']});d=applyCommand(d,{type:'tileset.add',tileset:{id:'ts',name:'Terrain',tileWidth:1,tileHeight:1,tiles:[{id:'t',pixels:[0]}]}});d=applyCommand(d,{type:'layer.add',layer:{id:'tiles',type:'tilemap'}});d=applyCommand(d,{type:'tilemap.paint',layerId:'tiles',tilesetId:'ts',columns:1,rows:1,points:[{x:0,y:0,tileId:'t'}]});d=applyCommand(d,{type:'frame.duplicate',frameIds:[d.frames[0].id],linked:true});d.frames[1].palette=['#0000ffff','#00ff00ff'];const files=unzipSync(makeGamePackage(d)),manifest=json(files['manifest.json']);assert.equal(manifest.tilesets.length,2);assert.equal(manifest.maps.length,2);const first=tiledRender(files,json(files[manifest.maps[0].source])),second=tiledRender(files,json(files[manifest.maps[1].source]));assert.deepEqual(first,Uint8Array.of(255,0,0,255));assert.deepEqual(second,Uint8Array.of(0,0,255,255));});
