import test from 'node:test';
import assert from 'node:assert/strict';
import { zlibSync, unzipSync } from 'fflate';
import {readAseprite,writeAseprite,readPng,writePng,importGif,encodeGif,packAtlas,makeSpriteSheet,importSheet,makeSequenceZip,importSequence} from '../app/formats.mjs';
const pixel=(r=255,g=0,b=0,a=255)=>Uint8Array.of(r,g,b,a);
const doc=()=>({format:'pixelwall-document',version:4,id:'test',name:'Test',width:8,height:8,colorMode:'rgba',palette:['#00000000','#ff0000ff','#808080ff'],colorProfile:'sRGB',layers:[{id:'group',name:'Group',type:'group',parentId:null,visible:true,locked:false,opacity:0.6,blendMode:'multiply'},{id:'art',name:'Artwork',type:'image',parentId:'group',visible:true,locked:true,opacity:0.8,blendMode:'screen'}],frames:[{id:'one',durationMs:120,cels:{art:{imageId:'shared',x:-2,y:3,opacity:0.4,zIndex:1}}},{id:'two',durationMs:230,cels:{art:{imageId:'shared',x:4,y:1,opacity:1}}}],images:{shared:{width:2,height:1,pixels:['#ff0000ff','#00440088']}},clips:[{id:'clip',name:'Walk',frameIds:['one','two'],direction:'pingpong_reverse',loop:true}],slices:[{id:'slice',name:'Foot',keys:[{frameId:'one',x:0,y:2,width:4,height:2,pivot:{x:2,y:1},center:{x:1,y:0,width:2,height:2}}]}],tilesets:[],metadata:{}});
test('Aseprite header and round-trip preserve groups, positions, linked cels, tags, slices and opacity',()=>{const encoded=writeAseprite(doc()),header=new DataView(encoded.buffer);assert.equal(header.getUint16(4,true),0xa5e0);assert.equal(header.getUint32(0,true),encoded.length);const {document:d,warnings}=readAseprite(encoded);assert.deepEqual(warnings,[]);assert.equal(d.layers[1].parentId,d.layers[0].id);assert.equal(d.layers[0].blendMode,'multiply');assert.equal(d.layers[1].locked,true);assert.equal(d.layers[0].opacity,0.6);assert.equal(d.frames[0].cels['layer-2'].x,-2);assert.equal(d.frames[1].cels['layer-2'].imageId,d.frames[0].cels['layer-2'].imageId);assert.equal(d.frames[1].durationMs,230);assert.equal(d.clips[0].direction,'pingpong_reverse');assert.deepEqual(d.slices[0].keys[0].pivot,{x:2,y:1});assert.deepEqual(d.images[d.frames[0].cels['layer-2'].imageId].pixels,['#ff0000ff','#00440088']);});
test('Aseprite preserves indexed values and palette animation',()=>{const d=doc();d.colorMode='indexed';d.images.shared.pixels=[1,0];d.frames[1].palette=['#00000000','#00ff00ff','#808080ff'];d.metadata.aseprite={transparentIndex:0};const r=readAseprite(writeAseprite(d)).document;assert.equal(r.colorMode,'indexed');assert.deepEqual(r.images[Object.keys(r.images)[0]].pixels,[1,0]);assert.equal(r.frames[1].palette[1],'#00ff00ff');});
test('Aseprite supports grayscale and prevents lossy grayscale writes',()=>{const d=doc();d.colorMode='grayscale';assert.throws(()=>writeAseprite(d),/non-grayscale/);d.images.shared.pixels=['#808080bb',null];const r=readAseprite(writeAseprite(d)).document;assert.deepEqual(r.images[Object.keys(r.images)[0]].pixels,['#808080bb','#00000000']);});
test('Aseprite preserves ICC profile bytes, user properties and precise bounds',()=>{const d=doc();d.metadata.aseprite={colorProfile:{type:2,flags:0,gamma:0,icc:[0,1,2,3]}};d.layers[1].userData={text:'Pixel ©',color:'#12345678',propertiesBytes:[8,0,0,0,0,0,0,0]};d.frames[0].cels.art.preciseBounds={flags:1,x:1.5,y:2.25,width:4.5,height:6.125};const {document:r,warnings}=readAseprite(writeAseprite(d));assert.deepEqual(r.metadata.aseprite.colorProfile.icc,[0,1,2,3]);assert.ok(warnings.some(w=>w.includes('ICC')));assert.deepEqual(r.layers[1].userData,d.layers[1].userData);assert.equal(r.frames[0].cels['layer-2'].preciseBounds.height,6.125);});
test('Aseprite tileset and flipped tilemap bits round-trip',()=>{const d=doc();d.layers=[{id:'tiles',name:'Tiles',parentId:null,type:'tilemap',tilesetId:'t',opacity:1,visible:true,blendMode:'normal'}];d.tilesets=[{id:'t',asepriteId:43,name:'Ground',flags:6,tileWidth:1,tileHeight:1,tileCount:2,baseIndex:1,imageId:'atlas'}];d.images={atlas:{width:1,height:2,pixels:[null,'#ff0000ff']},map:{width:2,height:1,pixels:[],tilemap:{bitsPerTile:32,idMask:0x1fffffff,xFlipMask:0x80000000,yFlipMask:0x40000000,diagonalFlipMask:0x20000000,tiles:[0,0x80000001]}}};d.frames=[{id:'one',durationMs:100,cels:{tiles:{imageId:'map',x:2,y:3,opacity:1}}}];d.clips=[];d.slices=[];const r=readAseprite(writeAseprite(d)).document;assert.equal(r.layers[0].tilesetId,'tileset-43');assert.deepEqual(r.images['image-1-1'].tilemap.tiles,[0,0x80000001]);assert.deepEqual(r.images['tileset-image-43'].pixels,['#00000000','#ff0000ff']);});
test('Aseprite rejects malformed and unsupported data rather than silently dropping it',()=>{const valid=writeAseprite(doc());assert.throws(()=>readAseprite(valid.slice(0,-1)),/size/);const d=doc();d.metadata.aseprite={opaqueChunks:[{type:123,data:[1]}]};assert.throws(()=>writeAseprite(d),/unsupported sprite chunks/);d.metadata={};d.clips[0].frameIds=['two','one'];assert.throws(()=>writeAseprite(d),/contiguous/);});
test('PNG preserves RGBA including translucent and transparent colors; detects corruption',()=>{const rgba=Uint8Array.of(100,20,50,0,0,128,255,128,255,255,255,255,22,99,55,1),png=writePng(2,2,rgba);assert.deepEqual(readPng(png).rgba,rgba);const corrupt=png.slice();corrupt[50]^=1;assert.throws(()=>readPng(corrupt),/checksum/);});
// Independent PNG chunk construction validates the reader against packed pixels and filters.
const be=n=>Uint8Array.of(n>>>24,n>>>16,n>>>8,n),join=(...a)=>Uint8Array.from(a.flatMap(x=>Array.from(x)));
function crc(data){let n=0xffffffff;for(const b of data){n^=b;for(let i=0;i<8;i++)n=n&1?(n>>>1)^0xedb88320:n>>>1;}return(n^0xffffffff)>>>0;}
function chunk(name,b){const t=new TextEncoder().encode(name);return join(be(b.length),t,b,be(crc(join(t,b))));}
function independentPng(w,h,depth,type,raw,extras=[],interlace=0){return join(Uint8Array.of(137,80,78,71,13,10,26,10),chunk('IHDR',join(be(w),be(h),[depth,type,0,0,interlace])),...extras,chunk('IDAT',zlibSync(raw)),chunk('IEND',[]));}
test('PNG decoder reads packed 1-bit indexed pixels with palette transparency',()=>{const png=independentPng(3,1,1,3,Uint8Array.of(0,0b01000000),[chunk('PLTE',[255,0,0,0,255,0]),chunk('tRNS',[255,0])]);assert.deepEqual(readPng(png).rgba,Uint8Array.of(255,0,0,255,0,255,0,0,255,0,0,255));});
test('PNG decoder reads 16-bit gray and Adam7 interlaced pixel passes',()=>{const gray=independentPng(1,1,16,0,Uint8Array.of(0,0x80,0x80));assert.deepEqual(readPng(gray).rgba,Uint8Array.of(128,128,128,255));const interlaced=independentPng(1,1,8,6,Uint8Array.of(0,10,20,30,40),[],1);assert.deepEqual(readPng(interlaced).rgba,Uint8Array.of(10,20,30,40));});
test('PNG decoder unfilters Sub, Up, Average and Paeth rows',()=>{for(let filter=1;filter<=4;filter++){const rgba=[10,20,30,40,50,60,70,80],delta=filter===1||filter===4?[10,20,30,40,40,40,40,40]:filter===2?rgba:[10,20,30,40,45,50,55,60],png=independentPng(2,1,8,6,Uint8Array.from([filter,...delta]));assert.deepEqual(Array.from(readPng(png).rgba),rgba);}});
test('GIF round-trip honors transparent pixels, frame disposal and durations',()=>{const entries=[{width:2,height:1,rgba:Uint8Array.of(255,0,0,255,0,0,0,0),durationMs:120},{width:2,height:1,rgba:Uint8Array.of(0,0,0,0,0,255,0,255),durationMs:230}];const d=importGif(encodeGif(entries)).document;assert.equal(d.frames.length,2);assert.equal(d.frames[1].durationMs,230);assert.deepEqual(d.images['image-2'].pixels,[null,'#00ff00ff']);});
test('Sheet slicing order and dimensions reproduce the source sequence',()=>{const entries=[{width:1,height:1,rgba:pixel(255,0,0)},{width:1,height:1,rgba:pixel(0,255,0)},{width:1,height:1,rgba:pixel(0,0,255)}],sheet=makeSpriteSheet(entries,{columns:2,padding:1}),d=importSheet(sheet,{cellWidth:1,cellHeight:1,spacing:1,count:3});assert.deepEqual(Object.values(d.images).map(i=>i.pixels[0]),['#ff0000ff','#00ff00ff','#0000ffff']);});
test('MaxRects atlas trims, extrudes, fits without overlap and records source coordinates',()=>{const entry={name:'red',width:3,height:3,rgba:new Uint8Array(36),durationMs:120};entry.rgba.set(pixel(),16);const atlas=packAtlas([entry,{name:'green',width:1,height:2,rgba:Uint8Array.of(0,255,0,255,0,255,0,255)}],{padding:2,extrude:1,powerOfTwo:true});assert.equal(Math.log2(atlas.width)%1,0);assert.equal(Math.log2(atlas.height)%1,0);const r=atlas.frames[0];assert.deepEqual(r.spriteSourceSize,{x:1,y:1,w:1,h:1});for(let y=r.frame.y-1;y<=r.frame.y+1;y++)for(let x=r.frame.x-1;x<=r.frame.x+1;x++)assert.deepEqual(atlas.rgba.slice((y*atlas.width+x)*4,(y*atlas.width+x)*4+4),pixel());assert.equal(r.duration,120);assert.throws(()=>packAtlas([entry,entry]),/unique/);assert.throws(()=>packAtlas([entry],{maxSize:1}),/do not fit/);});
test('PNG sequence ZIP includes actual PNG files and frame metadata',()=>{const files=unzipSync(makeSequenceZip([{width:1,height:1,rgba:pixel(),durationMs:140}]));assert.deepEqual(readPng(files['frame-0001.png']).rgba,pixel());assert.equal(JSON.parse(new TextDecoder().decode(files['metadata.json'])).frames[0].durationMs,140);assert.equal(importSequence([{width:1,height:1,rgba:pixel()}]).frames.length,1);});
test('non-looping GIF exports omit the loop extension',()=>{const result=importGif(encodeGif([{width:1,height:1,rgba:pixel(),durationMs:100}],{loop:-1}));assert.equal(result.document.metadata.gif.loopCount,null);});
test('atlas scale metadata scales slices and maps tags to the actual exported frames',()=>{const result=packAtlas([{id:'b',name:'f2',width:4,height:4,rgba:new Uint8Array(64)}],{scale:2,clips:[{id:'tag',name:'Run',frameIds:['a','b'],direction:'forward',loop:true}],slices:[{id:'slice',bounds:{x:1,y:2,width:3,height:4},pivot:{x:1,y:1}}]});assert.equal(result.meta.scale,'2');assert.deepEqual(result.meta.slices[0].bounds,{x:2,y:4,width:6,height:8});assert.deepEqual(result.meta.sourceSlices[0].bounds,{x:1,y:2,width:3,height:4});assert.deepEqual(result.meta.frameTags[0].frameIndices,[0]);assert.equal(result.meta.frameTags[0].partial,true);});
