import test from 'node:test';
import assert from 'node:assert/strict';
import {createDocument,normalizeDocument,applyCommand,renderFrame} from '../app/editor-core.mjs';
import {readAseprite,writeAseprite,readPng,writePng,importGif,encodeGif,importSequence} from '../app/formats.mjs';
test('raster format imports satisfy the shared document contract',()=>{const rgba=Uint8Array.of(255,0,0,255,0,0,0,0,0,255,0,128,0,0,255,255),png=readPng(writePng(2,2,rgba));const doc=normalizeDocument(importSequence([png]));assert.deepEqual(Array.from(renderFrame(doc)),Array.from(rgba));const gif=normalizeDocument(importGif(encodeGif([{width:2,height:2,rgba}])).document);assert.equal(gif.frames.length,1);});
test('native animated Aseprite slices, including hidden and off-canvas keys, normalize without loss',()=>{const d=createDocument({width:4,height:4});d.slices=[{id:'s',name:'Animated pivot',keys:[{frameId:d.frames[0].id,x:-2,y:-1,width:0,height:0,pivot:{x:3,y:4}}]}];const imported=normalizeDocument(readAseprite(writeAseprite(d)).document);assert.deepEqual(imported.slices[0].keys[0],{frameId:'frame-1',x:-2,y:-1,width:0,height:0,pivot:{x:3,y:4}});});
test('editable engine tilemaps export to Aseprite without changing rotation/flip pixels',()=>{for(const rotation of [0,90,180,270])for(const flipX of [false,true])for(const flipY of [false,true]){let d=createDocument({width:2,height:2});d=applyCommand(d,{type:'tileset.add',tileset:{id:'ts',name:'Test',tileWidth:2,tileHeight:2,tiles:[{id:'tile',pixels:['#ff0000ff','#00ff00ff','#0000ffff','#ffffffff']}]}});d=applyCommand(d,{type:'layer.add',layer:{id:'tilelayer',name:'Tiles',type:'tilemap'}});d=applyCommand(d,{type:'tilemap.paint',layerId:'tilelayer',tilesetId:'ts',columns:1,rows:1,points:[{x:0,y:0,tileId:'tile',rotate:rotation,flipX,flipY}]});const source=renderFrame(d),result=normalizeDocument(readAseprite(writeAseprite(d)).document);assert.deepEqual(Array.from(renderFrame(result)),Array.from(source),`rotation ${rotation}; flipX ${flipX}; flipY ${flipY}`);}});
test('new indexed projects reserve Aseprite transparency without erasing opaque index zero',()=>{const original=createDocument({width:2,height:1,colorMode:'indexed',palette:['#ff0000ff','#00ff00ff']});const d=applyCommand(original,{type:'cel.set',width:2,height:1,pixels:[0,null]});const imported=normalizeDocument(readAseprite(writeAseprite(d)).document);assert.equal(imported.metadata.aseprite.transparentIndex,2);assert.deepEqual(Array.from(renderFrame(imported)),Array.from(renderFrame(d)));assert.equal(d.palette.length,2);});
test('an imported Aseprite tilemap can be painted and manually edited without reindexing its tiles',()=>{let source=createDocument({name:'Native tile edit',width:4,height:2});source=applyCommand(source,{type:'tileset.add',tileset:{id:'ts',name:'Ground',tileWidth:2,tileHeight:2,tiles:[{id:'red',pixels:['#ff0000ff','#00ff00ff','#0000ffff','#ffffffff']},{id:'blue',pixels:['#0000ffff','#0000ffff','#0000ffff','#0000ffff']}]}});source=applyCommand(source,{type:'layer.add',layer:{id:'map',type:'tilemap'}});source=applyCommand(source,{type:'tilemap.paint',layerId:'map',tilesetId:'ts',columns:2,rows:1,points:[{x:0,y:0,tileId:'red'},{x:1,y:0,tileId:'blue'}]});source=applyCommand(source,{type:'frame.duplicate',frameIds:[source.frames[0].id],linked:true});let imported=normalizeDocument(readAseprite(writeAseprite(source)).document);const tileset=imported.tilesets[0],layer=imported.layers.find(l=>l.type==='tilemap'),first=imported.frames[0].id,second=imported.frames[1].id,before=Array.from(renderFrame(imported,first)),blue=tileset.tiles.find(t=>t.asepriteTileId===2);assert.ok(blue.sourceRect);imported=applyCommand(imported,{type:'tilemap.paint',layerId:layer.id,frameId:second,points:[{x:0,y:0,tileId:blue.id,rotate:90,flipX:true}]});let result=normalizeDocument(readAseprite(writeAseprite(imported)).document);assert.deepEqual(Array.from(renderFrame(result,first)),before);assert.deepEqual(Array.from(renderFrame(result,second)),Array.from(renderFrame(imported,second)));assert.equal(result.tilesets[0].tileCount,3);assert.equal(result.images[result.frames[1].cels[layer.id].imageId].tilemap.tiles[0]&0x1fffffff,2);imported=applyCommand(imported,{type:'tilemap.edit',layerId:layer.id,frameId:second,x:0,y:0,mode:'manual',pixels:['#ffffffff','#ffffffff','#ffffffff','#ffffffff']});result=normalizeDocument(readAseprite(writeAseprite(imported)).document);assert.deepEqual(Array.from(renderFrame(result,first)),Array.from(renderFrame(imported,first)));assert.deepEqual(Array.from(renderFrame(result,second)),Array.from(renderFrame(imported,second)));assert.equal(result.tilesets[0].tileCount,3);});
