import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,access} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {prepareOffline} from '../scripts/prepare-offline.mjs';
import {prepareVercel} from '../scripts/prepare-vercel-build.mjs';
const template=await readFile(new URL('../scripts/offline-worker.js',import.meta.url),'utf8');
async function fixture(t){const root=await mkdtemp(join(tmpdir(),'pixelwall-vercel-'));t.after(()=>rm(root,{recursive:true,force:true}));for(const dir of ['scripts','public','dist/client/assets','.next/static/chunks/[editor]','.next/server','.next/output/static','.next/types','.next/dev/types'])await mkdir(join(root,dir),{recursive:true});await writeFile(join(root,'scripts/offline-worker.js'),template);await writeFile(join(root,'.next/BUILD_ID'),'NEXT-BUILD-A');await writeFile(join(root,'.next/static/chunks/[editor]/index café #1%.js'),'console.log("editor")');await writeFile(join(root,'.next/static/chunks/editor.css'),'body{}');await writeFile(join(root,'.next/server/server.js'),'SERVER MUST NOT BE PUBLIC');await writeFile(join(root,'dist/client/assets/app.js'),'console.log("sites editor")');return root;}
test('Next inventory encodes URLs and excludes server files',async t=>{const root=await fixture(t),result=await prepareOffline({root,next:true});assert.deepEqual(result.assets,['/_next/static/chunks/%5Beditor%5D/index%20caf%C3%A9%20%231%25.js','/_next/static/chunks/editor.css']);assert.doesNotMatch(await readFile(join(root,'public/sw.js'),'utf8'),/__PIXELWALL_BUILD_ID__/);assert.equal(await readFile(join(root,'scripts/offline-worker.js'),'utf8'),template);});
test('postbuild overwrites stale adapter copies with current worker and inventory',async t=>{const root=await fixture(t);for(const name of ['sw.js','offline-assets.json'])await writeFile(join(root,'.next/output/static',name),'STALE');await prepareOffline({root,next:true});for(const name of ['sw.js','offline-assets.json'])assert.equal(await readFile(join(root,'.next/output/static',name),'utf8'),await readFile(join(root,'public',name),'utf8'));});
test('offline IDs are deterministic and change with the Next build',async t=>{const root=await fixture(t),a=await prepareOffline({root,next:true}),b=await prepareOffline({root,next:true});assert.equal(a.buildId,b.buildId);await writeFile(join(root,'.next/BUILD_ID'),'NEXT-BUILD-B');const c=await prepareOffline({root,next:true});assert.notEqual(a.buildId,c.buildId);});
test('Sites mode still generates into dist/client without touching the template',async t=>{const root=await fixture(t),result=await prepareOffline({root});assert.deepEqual(result.assets,['/assets/app.js']);assert.match(await readFile(join(root,'dist/client/sw.js'),'utf8'),new RegExp(result.buildId));assert.equal(await readFile(join(root,'scripts/offline-worker.js'),'utf8'),template);await assert.rejects(access(join(root,'public/sw.js')));});
test('Vercel prebuild cleans generated files and builds both downloads with canonical public storefront',async t=>{const root=await fixture(t),calls=[];for(const file of ['public/sw.js','public/offline-assets.json','.next/types/old.d.ts','.next/dev/types/old.d.ts'])await writeFile(join(root,file),'old');await prepareVercel({root,env:{PIXELWALL_SITE_URL:'https://private.example',PIXELWALL_STANDALONE_SITE_URL:'https://private.example',PIXELWALL_SOURCE_ROOT:'/wrong',PIXELWALL_CLI_ENTRY:'/wrong'},run:async(script,options)=>calls.push({script,...options})});assert.deepEqual(calls.map(call=>call.script),['scripts/build-standalone.mjs','scripts/package-downloads.mjs']);for(const call of calls){assert.equal(call.env.PIXELWALL_STANDALONE_SITE_URL,'https://www.pixelwall.dev');assert.equal(call.env.PIXELWALL_SOURCE_ROOT,root);assert.equal(call.env.PIXELWALL_CLI_ENTRY,join(root,'app/cli.mjs'));}for(const file of ['public/sw.js','public/offline-assets.json','.next/types/old.d.ts','.next/dev/types/old.d.ts'])await assert.rejects(access(join(root,file)));});
test('failed standalone build prevents packaging stale downloads',async t=>{const root=await fixture(t),calls=[];await assert.rejects(prepareVercel({root,env:{},run:async script=>{calls.push(script);throw Error('build failed');}}),/build failed/);assert.deepEqual(calls,['scripts/build-standalone.mjs']);});
test('standalone build ignores private storefront environment overrides',async()=>{const previous=process.env.PIXELWALL_STANDALONE_SITE_URL;try{process.env.PIXELWALL_STANDALONE_SITE_URL='https://private.example';const {standaloneConfig}=await import('../standalone/vite.config.mjs');const config=await standaloneConfig({sourceRoot:fileURLToPath(new URL('../',import.meta.url)),outDir:join(tmpdir(),'pixelwall-vercel-config-only')});assert.equal(config.define['process.env.NEXT_PUBLIC_PIXELWALL_SITE_URL'],JSON.stringify('https://www.pixelwall.dev'));assert.equal(config.envDir,false);assert.equal(config.define['process.env.STRIPE_SECRET_KEY'],undefined);}finally{if(previous===undefined)delete process.env.PIXELWALL_STANDALONE_SITE_URL;else process.env.PIXELWALL_STANDALONE_SITE_URL=previous;}});
