/** PixelWall portable formats. No DOM, filesystem, network, or license bypasses.
 * Aseprite codec follows https://github.com/aseprite/aseprite/blob/main/docs/ase-file-specs.md
 * Paid export entry points must be gated by their caller before invoking these codecs.
 */
import { zlibSync, unzlibSync, zipSync, strToU8 } from 'fflate';
import omggif from 'omggif';
import {renderExportFrame, toExportRGBA} from './export-render.mjs';
import {documentProfile, isSRGB} from './color-management.mjs';
const { GifReader, GifWriter } = omggif;
const encoder = new TextEncoder(), decoder = new TextDecoder();
export const ASEPRITE_BLEND_MODES = ['normal','multiply','screen','overlay','darken','lighten','color-dodge','color-burn','hard-light','soft-light','difference','exclusion','hue','saturation','color','luminosity','addition','subtract','divide'];
const DIRECTIONS = ['forward','reverse','pingpong','pingpong_reverse'];
const MAX_PIXELS = 64 * 1024 * 1024;
function assert(value, message) { if (!value) throw new Error(message); }
function bytes(value) { return value instanceof Uint8Array ? value : new Uint8Array(value); }
function dimensions(w,h) { assert(Number.isInteger(w)&&Number.isInteger(h)&&w>0&&h>0&&w*h<=MAX_PIXELS, 'Invalid or excessive image dimensions.'); }
function hex(r,g,b,a=255) { return '#'+[r,g,b,a].map(v=>v.toString(16).padStart(2,'0')).join(''); }
export function colorRgba(value, palette=[]) {
  if (typeof value==='number') value=palette[value];
  if (value==null) return [0,0,0,0];
  assert(typeof value==='string' && /^#[0-9a-f]{6}([0-9a-f]{2})?$/i.test(value), `Invalid pixel color ${value}.`);
  return [parseInt(value.slice(1,3),16),parseInt(value.slice(3,5),16),parseInt(value.slice(5,7),16),value.length===9?parseInt(value.slice(7,9),16):255];
}
export function pixelsToRgba(pixels,palette=[]) { const out=new Uint8Array(pixels.length*4); pixels.forEach((p,i)=>out.set(colorRgba(p,palette),i*4)); return out; }
export function rgbaToPixels(rgba) { const out=[]; for(let i=0;i<rgba.length;i+=4) out.push(rgba[i+3]?hex(...rgba.subarray(i,i+4)):null); return out; }
class Reader {
  constructor(data) { this.b=bytes(data); this.v=new DataView(this.b.buffer,this.b.byteOffset,this.b.byteLength); this.p=0; }
  need(n) { assert(Number.isSafeInteger(n)&&n>=0&&this.p+n<=this.b.length,'Truncated or malformed binary file.'); }
  u8(){this.need(1);return this.v.getUint8(this.p++);} u16(){this.need(2);const v=this.v.getUint16(this.p,true);this.p+=2;return v;}
  i16(){this.need(2);const v=this.v.getInt16(this.p,true);this.p+=2;return v;} u32(){this.need(4);const v=this.v.getUint32(this.p,true);this.p+=4;return v;}
  i32(){this.need(4);const v=this.v.getInt32(this.p,true);this.p+=4;return v;} skip(n){this.need(n);this.p+=n;return this;} take(n){this.need(n);const v=this.b.slice(this.p,this.p+n);this.p+=n;return v;}
  str(){return decoder.decode(this.take(this.u16()));} remaining(){return this.take(this.b.length-this.p);}
}
class Writer {
  constructor(){this.b=[];} u8(v){this.b.push(v&255);return this;} u16(v){return this.u8(v).u8(v>>>8);} i16(v){return this.u16(v);} u32(v){return this.u16(v).u16(v>>>16);} i32(v){return this.u32(v);}
  raw(v){for(const x of v)this.b.push(x);return this;} zero(n){for(let i=0;i<n;i++)this.b.push(0);return this;} str(v){const b=encoder.encode(v||'');assert(b.length<=65535,'Sprite name exceeds 65535 UTF-8 bytes.');return this.u16(b.length).raw(b);} done(){return Uint8Array.from(this.b);}
}
function concat(parts){const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let p=0;for(const v of parts){out.set(v,p);p+=v.length;}return out;}
function inflateExact(compressed,length){assert(length<=MAX_PIXELS*4,'Decompressed image exceeds safety limit.');const out=unzlibSync(compressed,{out:new Uint8Array(length+1)});assert(out.length===length,'Image data length does not match its dimensions.');let a=1,b=0;for(const byte of out){a=(a+byte)%65521;b=(b+a)%65521;}const p=compressed.length-4,checksum=((compressed[p]<<24)|(compressed[p+1]<<16)|(compressed[p+2]<<8)|compressed[p+3])>>>0;assert((((b<<16)|a)>>>0)===checksum,'Compressed image checksum mismatch.');return out;}
function decodePixels(data,w,h,depth){dimensions(w,h);const channels=depth/8;assert(data.length===w*h*channels,'Sprite cel data has incorrect length.');const out=new Array(w*h);for(let i=0;i<out.length;i++){const p=i*channels;out[i]=depth===8?data[p]:depth===16?hex(data[p],data[p],data[p],data[p+1]):hex(data[p],data[p+1],data[p+2],data[p+3]);}return out;}
function encodePixels(image,depth,palette,transparentIndex=0){dimensions(image.width,image.height);assert(image.pixels?.length===image.width*image.height,'Image pixel count does not match dimensions.');const out=new Uint8Array(image.pixels.length*depth/8);image.pixels.forEach((v,i)=>{if(depth===8){const index=v==null?transparentIndex:typeof v==='number'?v:palette.findIndex(p=>p.toLowerCase()===v.toLowerCase());assert(Number.isInteger(index)&&index>=0&&index<Math.min(palette.length,256),`Pixel ${i} is not in the indexed palette.`);out[i]=index;}else{const [r,g,b,a]=colorRgba(v,palette);if(depth===16){assert(r===g&&g===b,'Grayscale sprite export contains a non-grayscale pixel. Convert color mode first.');out.set([r,a],i*2);}else out.set([r,g,b,a],i*4);}});return out;}
function baseDocument(w,h,name='Imported sprite') { dimensions(w,h);return {format:'pixelwall-document',version:4,id:'document-import',name,width:w,height:h,colorMode:'rgba',palette:['#00000000','#000000ff','#ffffffff'],colorProfile:'sRGB',layers:[],frames:[],images:{},clips:[],slices:[],tilesets:[],metadata:{}}; }
function imageDocument(entries,options={}) {assert(entries.length>0,'No images to import.');const width=options.width||Math.max(...entries.map(e=>e.width)),height=options.height||Math.max(...entries.map(e=>e.height));const doc=baseDocument(width,height,options.name);doc.layers=[{id:'layer-1',name:'Artwork',type:'image',parentId:null,visible:true,locked:false,opacity:1,blendMode:'normal'}];for(const [i,e] of entries.entries()){dimensions(e.width,e.height);assert(e.rgba.length===e.width*e.height*4,'RGBA data length is invalid.');const id=`image-${i+1}`;doc.images[id]={width:e.width,height:e.height,pixels:rgbaToPixels(e.rgba)};doc.frames.push({id:`frame-${i+1}`,durationMs:e.durationMs||options.durationMs||100,cels:{'layer-1':{imageId:id,x:e.x||0,y:e.y||0,opacity:1}}});}return doc;}
export function importSequence(entries,options={}) { return imageDocument(entries,options); }

export function readAseprite(input) {
 const data=bytes(input),r=new Reader(data);assert(data.length>=128,'Sprite header is truncated.');const size=r.u32();assert(size===data.length,'Sprite file size does not match header.');assert(r.u16()===0xa5e0,'Not a supported sprite file.');const count=r.u16(),width=r.u16(),height=r.u16(),depth=r.u16();assert([8,16,32].includes(depth),'Unsupported sprite color depth.');assert(count>0,'Sprite has no frames.');const flags=r.u32(),speed=r.u16();r.skip(8);const transparentIndex=r.u8();r.skip(3);const colors=r.u16()||256,pixelWidth=r.u8()||1,pixelHeight=r.u8()||1,grid={x:r.i16(),y:r.i16(),width:r.u16(),height:r.u16()};r.p=128;
 const doc=baseDocument(width,height),warnings=[],meta={transparentIndex,pixelRatio:{width:pixelWidth,height:pixelHeight},grid,flags,paletteNames:{},externalFiles:[],opaqueChunks:[]};doc.colorMode={8:'indexed',16:'grayscale',32:'rgba'}[depth];doc.metadata.aseprite=meta;
 let palette=Array.from({length:colors},()=> '#000000ff'),paletteSeen=false,anyPalette=false,parents=[],lastObject=doc,pendingUserObjects=[],pendingTile=null;const links=[];
 for(let fi=0;fi<count;fi++){
  const start=r.p,frameSize=r.u32();assert(frameSize>=16&&start+frameSize<=data.length,'Invalid sprite frame size.');assert(r.u16()===0xf1fa,'Invalid sprite frame magic.');const oldCount=r.u16(),duration=r.u16();r.skip(2);const chunkCount=r.u32()||oldCount;const frame={id:`frame-${fi+1}`,durationMs:duration||speed||100,cels:{}};doc.frames.push(frame);let paletteChanged=false;
  for(let ci=0;ci<chunkCount;ci++){
   const cs=r.p,chunkSize=r.u32(),type=r.u16();assert(chunkSize>=6&&cs+chunkSize<=start+frameSize,'Invalid sprite chunk size.');const raw=r.take(chunkSize-6),c=new Reader(raw);
   if(type!==0x2020){pendingUserObjects=[];pendingTile=null;}
   if(type===0x2004){
    assert(fi===0,'Per-frame layer definitions are not supported.');const layerFlags=c.u16(),layerType=c.u16(),level=c.u16();c.skip(4);const blend=c.u16(),opacity=c.u8();c.skip(3);const name=c.str();assert(layerType<=2,'Unsupported sprite layer type.');assert(blend<ASEPRITE_BLEND_MODES.length,'Unsupported sprite blend mode.');assert(level===0||parents[level-1], 'Invalid sprite layer hierarchy.');
    const layer={id:`layer-${doc.layers.length+1}`,name,type:layerType===1?'group':layerType===2?'tilemap':layerFlags&64?'reference':'image',parentId:level?parents[level-1].id:null,visible:!!(layerFlags&1),locked:!(layerFlags&2),opacity:layerType===1?flags&2?opacity/255:1:flags&1?opacity/255:1,blendMode:layerType===1&&!(flags&2)?'normal':ASEPRITE_BLEND_MODES[blend],asepriteFlags:layerFlags};
    if(layerType===2)layer.asepriteTilesetIndex=c.u32();if(flags&4)layer.uuid=Array.from(c.take(16));doc.layers.push(layer);parents.length=level;parents[level]=layer;lastObject=layer;
   } else if(type===0x2005){
    const li=c.u16(),x=c.i16(),y=c.i16(),opacity=c.u8()/255,celType=c.u16(),zIndex=c.i16();c.skip(5);const layer=doc.layers[li];assert(layer,'Sprite cel references a missing layer.');assert(!frame.cels[layer.id],'Duplicate cel for one layer/frame is unsupported.');const cel={imageId:'',x,y,opacity,zIndex};frame.cels[layer.id]=cel;lastObject=cel;
    if(celType===1){links.push({cel,fi,li,target:c.u16()});}
    else if(celType===0||celType===2){const w=c.u16(),h=c.u16();dimensions(w,h);const payload=celType===0?c.remaining():inflateExact(c.remaining(),w*h*depth/8);cel.imageId=`image-${fi+1}-${li+1}`;doc.images[cel.imageId]={width:w,height:h,pixels:decodePixels(payload,w,h,depth)};}
    else if(celType===3){const w=c.u16(),h=c.u16(),bitsPerTile=c.u16();dimensions(w,h);assert([8,16,32].includes(bitsPerTile),'Unsupported sprite tile bit depth.');const tilemap={bitsPerTile,idMask:c.u32(),xFlipMask:c.u32(),yFlipMask:c.u32(),diagonalFlipMask:c.u32()};c.skip(10);const tr=new Reader(inflateExact(c.remaining(),w*h*bitsPerTile/8));tilemap.tiles=Array.from({length:w*h},()=>bitsPerTile===32?tr.u32():bitsPerTile===16?tr.u16():tr.u8());cel.imageId=`image-${fi+1}-${li+1}`;doc.images[cel.imageId]={width:w,height:h,pixels:[],tilemap};}
    else throw new Error(`Unsupported sprite cel type ${celType}.`);
   } else if(type===0x2006){assert(lastObject&&'imageId' in lastObject,'Cel extra has no preceding cel.');const extraFlags=c.u32();lastObject.preciseBounds={flags:extraFlags,x:c.i32()/65536,y:c.i32()/65536,width:c.i32()/65536,height:c.i32()/65536};c.skip(16);}
   else if(type===0x2007){const profile={type:c.u16(),flags:c.u16(),gamma:c.i32()/65536};c.skip(8);if(profile.type===2)profile.icc=Array.from(c.take(c.u32()));meta.colorProfile=profile;if(profile.type===2||(profile.flags&1))warnings.push('Embedded ICC / fixed-gamma profile retained for color-managed preview and export.');}
   else if(type===0x2008){const n=c.u32();c.skip(8);for(let i=0;i<n;i++){const entry={id:c.u32(),type:c.u8()};c.skip(7);entry.name=c.str();meta.externalFiles.push(entry);}}
   else if(type===0x2019){const n=c.u32(),first=c.u32(),last=c.u32();assert(n>0&&n<=65536&&first<=last&&last<n,'Invalid sprite palette.');c.skip(8);palette.length=n;for(let i=first;i<=last;i++){const f=c.u16();palette[i]=hex(c.u8(),c.u8(),c.u8(),c.u8());if(f&1)meta.paletteNames[i]=c.str();}palette=Array.from(palette,p=>p||'#000000ff');paletteSeen=true;anyPalette=true;paletteChanged=true;lastObject=doc;}
   else if(type===0x0004||type===0x0011){anyPalette=true;if(!paletteSeen){const n=c.u16();let index=0;for(let i=0;i<n;i++){index+=c.u8();const ct=c.u8()||256;for(let j=0;j<ct;j++){const rgb=[c.u8(),c.u8(),c.u8()].map(v=>type===0x0011?Math.round(v*255/63):v);palette[index++]=hex(...rgb);}}paletteChanged=true;}}
   else if(type===0x2018){const n=c.u16();c.skip(8);for(let i=0;i<n;i++){const from=c.u16(),to=c.u16(),direction=c.u8(),repeat=c.u16();assert(from<=to&&to<count&&direction<=3,'Invalid sprite animation tag.');c.skip(6);const color=hex(c.u8(),c.u8(),c.u8());c.skip(1);const clip={id:`clip-${doc.clips.length+1}`,name:c.str(),frameIds:Array.from({length:to-from+1},(_,j)=>`frame-${from+j+1}`),direction:DIRECTIONS[direction],loop:repeat===0,repeat,color};doc.clips.push(clip);pendingUserObjects.push(clip);}lastObject=doc;}
   else if(type===0x2022){const n=c.u32(),sliceFlags=c.u32();c.skip(4);const slice={id:`slice-${doc.slices.length+1}`,name:c.str(),keys:[]};for(let i=0;i<n;i++){const frameIndex=c.u32();assert(frameIndex<count,'Slice refers to an unknown frame.');const key={frameId:`frame-${frameIndex+1}`,x:c.i32(),y:c.i32(),width:c.u32(),height:c.u32()};if(sliceFlags&1)key.center={x:c.i32(),y:c.i32(),width:c.u32(),height:c.u32()};if(sliceFlags&2)key.pivot={x:c.i32(),y:c.i32()};slice.keys.push(key);}doc.slices.push(slice);lastObject=slice;}
   else if(type===0x2023){const numericId=c.u32(),tileFlags=c.u32(),tileCount=c.u32(),tileWidth=c.u16(),tileHeight=c.u16(),baseIndex=c.i16();c.skip(14);const tileset={id:`tileset-${numericId}`,asepriteId:numericId,name:c.str(),flags:tileFlags,tileCount,tileWidth,tileHeight,baseIndex};dimensions(tileWidth,tileHeight*Math.max(1,tileCount));if(tileFlags&1){tileset.externalFileId=c.u32();tileset.externalTilesetId=c.u32();warnings.push(`Tileset “${tileset.name}” links an external file; external content is not loaded automatically.`);}if(tileFlags&2){const compressed=c.take(c.u32()),h=tileHeight*tileCount;tileset.imageId=`tileset-image-${numericId}`;doc.images[tileset.imageId]={width:tileWidth,height:h,pixels:decodePixels(inflateExact(compressed,tileWidth*h*depth/8),tileWidth,h,depth)};}doc.tilesets.push(tileset);lastObject=tileset;pendingTile={tileset,index:-1};}
   else if(type===0x2020){const uflags=c.u32(),userData={};if(uflags&1)userData.text=c.str();if(uflags&2)userData.color=hex(c.u8(),c.u8(),c.u8(),c.u8());if(uflags&4){const len=c.u32();assert(len>=8,'Invalid sprite property block.');const prop=new Writer().u32(len).raw(c.take(len-4));userData.propertiesBytes=Array.from(prop.done());warnings.push('Sprite extension properties are preserved as opaque data.');}assert(!(uflags&~7),'Unsupported sprite user-data flags.');if(pendingUserObjects.length)pendingUserObjects.shift().userData=userData;else if(pendingTile){if(pendingTile.index<0)pendingTile.tileset.userData=userData;else{pendingTile.tileset.tileUserData||=[];pendingTile.tileset.tileUserData[pendingTile.index]=userData;}pendingTile.index++;}else lastObject.userData=userData;}
   else {meta.opaqueChunks.push({frameIndex:fi,type,data:Array.from(raw)});warnings.push(`Unsupported sprite chunk 0x${type.toString(16)} preserved in the project; native re-export is blocked to prevent data loss.`);}
  }
  assert(r.p===start+frameSize,'Frame size/chunk count mismatch.');if(paletteChanged||fi===0)frame.palette=[...palette];
 }
 assert(r.p===data.length,'Unexpected bytes after sprite frames.');
 const resolve=(link,seen=new Set())=>{assert(link.target<count,'Linked cel references an unknown frame.');assert(!seen.has(link),'Cyclic linked sprite cels.');seen.add(link);const target=doc.frames[link.target].cels[doc.layers[link.li].id];assert(target,'Linked cel references an empty cel.');if(!target.imageId){const other=links.find(l=>l.cel===target);assert(other,'Missing linked cel target.');resolve(other,seen);}link.cel.imageId=target.imageId;};links.forEach(l=>resolve(l));
 for(const layer of doc.layers)if(layer.type==='tilemap'){const ts=doc.tilesets[layer.asepriteTilesetIndex];assert(ts,'Tilemap references an unknown tileset.');layer.tilesetId=ts.id;}
 doc.palette=[...(doc.frames[0].palette||palette)];if(doc.colorMode==='indexed'&&!anyPalette)warnings.push('Indexed file has no explicit palette.');
 meta.warnings=[...new Set(warnings)];return {document:doc,warnings:meta.warnings};
}
function aseChunk(type,w){const b=w instanceof Writer?w.done():w;return new Writer().u32(b.length+6).u16(type).raw(b).done();}
function userChunk(obj){if(!obj?.userData)return [];const u=obj.userData,w=new Writer().u32((u.text!=null?1:0)|(u.color?2:0)|(u.propertiesBytes?4:0));if(u.text!=null)w.str(u.text);if(u.color)w.raw(colorRgba(u.color));if(u.propertiesBytes)w.raw(u.propertiesBytes);return [aseChunk(0x2020,w)];}
function paletteChunk(palette,names={}){assert(palette.length>0,'Indexed export requires a palette.');const w=new Writer().u32(palette.length).u32(0).u32(palette.length-1).zero(8);palette.forEach((p,i)=>{w.u16(names[i]?1:0).raw(colorRgba(p));if(names[i])w.str(names[i]);});return aseChunk(0x2019,w);}

// Convert editable PixelWall tile definitions into native Aseprite embedded tilesets.
function tileImage(doc,tile){const image=doc.images[tile.imageId];assert(image&&!image.tilemap,'Tile raster image is missing.');if(!tile.sourceRect)return image;const {x,y,width,height}=tile.sourceRect;assert([x,y,width,height].every(Number.isInteger)&&x>=0&&y>=0&&width>0&&height>0&&x+width<=image.width&&y+height<=image.height,'Tile source rectangle exceeds its atlas.');const pixels=[];for(let yy=0;yy<height;yy++)for(let xx=0;xx<width;xx++)pixels.push(image.pixels[(y+yy)*image.width+x+xx]);return {width,height,pixels};}
function prepareNativeTiles(input){
 if(!input.layers.some(l=>l.tilemaps&&Object.keys(l.tilemaps).length)&&!input.tilesets?.some(t=>t.tiles?.length))return input;
 const doc=structuredClone(input),indices=new Map();
 for(const ts of doc.tilesets){if(!Array.isArray(ts.tiles))continue;const ids=new Map(),native=Number.isInteger(ts.asepriteId)&&ts.imageId&&doc.images[ts.imageId],original=native?doc.images[ts.imageId]:null,transparent=doc.colorMode==='indexed'?(doc.metadata?.aseprite?.transparentIndex??0):null;let nextIndex=native?ts.tileCount:1;const assignments=[];
  for(const tile of ts.tiles){const raw=native&&Number.isInteger(tile.asepriteTileId)?tile.asepriteTileId:nextIndex++;assert(raw>=0&&raw<0x1fffffff,'Tile ID exceeds the native range.');nextIndex=Math.max(nextIndex,raw+1);ids.set(tile.id,raw);assignments.push({tile,index:raw});}
  const pixels=new Array(ts.tileWidth*ts.tileHeight*nextIndex).fill(transparent);if(original){assert(original.width===ts.tileWidth&&original.height===ts.tileHeight*ts.tileCount,'Native tileset atlas shape is invalid.');for(let i=0;i<original.pixels.length;i++)pixels[i]=original.pixels[i];}
  for(const {tile,index}of assignments){if(tile.userData!==undefined){ts.tileUserData??=[];ts.tileUserData[index]=structuredClone(tile.userData);}const image=tileImage(doc,tile);assert(image.width===ts.tileWidth&&image.height===ts.tileHeight,'Tile dimensions do not match their tileset.');const offset=index*ts.tileWidth*ts.tileHeight;for(let i=0;i<image.pixels.length;i++)pixels[offset+i]=image.pixels[i];}
  indices.set(ts.id,ids);ts.imageId=`ase-tileset-${ts.id}`;ts.tileCount=nextIndex;ts.flags=native?(ts.flags|2):(ts.flags||0)|6;doc.images[ts.imageId]={width:ts.tileWidth,height:ts.tileHeight*ts.tileCount,pixels};
 }
 const links=new Map();for(const layer of doc.layers){if(!layer.tilemaps)continue;for(const [frameId,map]of Object.entries(layer.tilemaps)){
  const frame=doc.frames.find(f=>f.id===frameId);assert(frame,'Tilemap references a missing frame.');assert(!layer.tilesetId||layer.tilesetId===map.tilesetId,'Sprite tilemap layer cannot switch tilesets between frames.');layer.tilesetId=map.tilesetId;const ids=indices.get(map.tilesetId),ts=doc.tilesets.find(t=>t.id===map.tilesetId);assert(ids&&ts,'Tilemap requires an embedded tileset.');const columns=map.columns,rows=map.rows;dimensions(columns,rows);assert(map.cells.length===columns*rows,'Tilemap cell count does not match dimensions.');const tilemap={bitsPerTile:32,idMask:0x1fffffff,xFlipMask:0x80000000,yFlipMask:0x40000000,diagonalFlipMask:0x20000000,tiles:map.cells.map(cell=>{if(cell==null)return ts.flags&4?0:0xffffffff;const id=ids.get(cell.tileId);assert(id!=null,'Tilemap references an unknown tile.');let fx=!!cell.flipX,fy=!!cell.flipY,d=false;const rotation=((cell.rotate||0)%360+360)%360;assert([0,90,180,270].includes(rotation),'Sprite tiles require quarter-turn rotations.');if(rotation===90){d=true;[fx,fy]=[!fy,fx];}if(rotation===180){fx=!fx;fy=!fy;}if(rotation===270){d=true;[fx,fy]=[fy,!fx];}return(id|(fx?0x80000000:0)|(fy?0x40000000:0)|(d?0x20000000:0))>>>0;})};
  const previous=frame.cels[layer.id],sourceId=map.sourceImageId||previous?.imageId,old=doc.images[sourceId],unchanged=old?.tilemap&&old.width===columns&&old.height===rows&&JSON.stringify(old.tilemap)===JSON.stringify(tilemap),key=sourceId?`${layer.id}:${sourceId}:${JSON.stringify(tilemap)}`:null;let imageId=unchanged?sourceId:key&&links.get(key);if(!imageId){imageId=`ase-map-${layer.id}-${frameId}`;doc.images[imageId]={width:columns,height:rows,pixels:[],tilemap};if(key)links.set(key,imageId);}frame.cels[layer.id]={...(previous||{x:map.x||0,y:map.y||0,opacity:1}),imageId};
 }}return doc;
}

function prepareIndexedTransparency(input){
 if(input.colorMode!=='indexed'||Number.isInteger(input.metadata?.aseprite?.transparentIndex))return input;
 const doc=structuredClone(input),palettes=[doc.palette,...doc.frames.filter(f=>f.palette).map(f=>f.palette)],length=Math.max(...palettes.map(p=>p.length)),used=new Set();for(const image of Object.values(doc.images))if(!image.tilemap)for(const pixel of image.pixels)if(pixel!=null)used.add(typeof pixel==='number'?pixel:doc.palette.findIndex(p=>p.toLowerCase()===pixel.toLowerCase()));
 let index=doc.palette.findIndex((p,i)=>colorRgba(p)[3]===0&&palettes.every(palette=>!palette[i]||colorRgba(palette[i])[3]===0));if(index<0){if(length<256)index=length;else index=Array.from({length:256},(_,i)=>i).find(i=>!used.has(i));}
 assert(Number.isInteger(index),'Indexed sprite needs a reserved transparent palette entry. Free a palette slot or convert the document to RGBA before export.');for(const palette of palettes){while(palette.length<=index)palette.push('#000000ff');palette[index]='#00000000';}doc.metadata||={};doc.metadata.aseprite={...(doc.metadata.aseprite||{}),transparentIndex:index};return doc;
}
export function writeAseprite(input){
 const doc=prepareNativeTiles(prepareIndexedTransparency(input));
 dimensions(doc.width,doc.height);assert(doc.width<=65535&&doc.height<=65535,'Sprite dimensions exceed 65535.');assert(doc.frames.length>0&&doc.frames.length<=65535,'Sprite supports 1–65535 frames.');const meta=doc.metadata?.aseprite||{};assert(!meta.opaqueChunks?.length,'Native export blocked: unsupported sprite chunks are retained in this project. Save the PixelWall project to preserve them.');const depth={rgba:32,indexed:8,grayscale:16}[doc.colorMode];assert(depth,'Unsupported color mode.');assert(depth!==8||(doc.palette.length>0&&doc.palette.length<=256),'Indexed sprite requires a palette of 1–256 colors.');
 const layers=[],walk=(parent,ancestors=[])=>{for(const l of doc.layers.filter(l=>(l.parentId||null)===parent)){assert(!ancestors.includes(l.id),'Cyclic layer hierarchy.');layers.push(l);walk(l.id,[...ancestors,l.id]);}};walk(null);assert(layers.length===doc.layers.length,'Layer hierarchy contains a missing parent or cycle.');assert(layers.length<=65535,'Too many sprite layers.');const frames=[],seenImages=new Map(),hasUuid=layers.some(l=>l.uuid);
 for(let fi=0;fi<doc.frames.length;fi++){
 const frame=doc.frames[fi],chunks=[];assert(Number.isInteger(frame.durationMs)&&frame.durationMs>0&&frame.durationMs<=65535,'Sprite frame duration must be 1–65535 ms.');
 if(fi===0){
 const cp=meta.colorProfile||{type:1,flags:0,gamma:0},cw=new Writer().u16(cp.type).u16(cp.flags).i32(Math.round(cp.gamma*65536)).zero(8);if(cp.type===2){assert(cp.icc?.length,'Missing embedded color profile.');cw.u32(cp.icc.length).raw(cp.icc);}chunks.push(aseChunk(0x2007,cw));
 if(meta.externalFiles?.length){const w=new Writer().u32(meta.externalFiles.length).zero(8);for(const e of meta.externalFiles)w.u32(e.id).u8(e.type).zero(7).str(e.name);chunks.push(aseChunk(0x2008,w));}
 const initialPalette=frame.palette||doc.palette;if(initialPalette?.length)chunks.push(paletteChunk(initialPalette,meta.paletteNames),...userChunk(doc));
 for(const [ti,ts] of (doc.tilesets||[]).entries()){
  assert(!ts.tiles?.length||ts.imageId,'Native tileset export requires a stacked atlas image.');const flags=(ts.flags??4)|(ts.imageId?2:0)|(ts.externalFileId!=null?1:0),w=new Writer().u32(ts.asepriteId??ti).u32(flags).u32(ts.tileCount).u16(ts.tileWidth).u16(ts.tileHeight).i16(ts.baseIndex??1).zero(14).str(ts.name);if(flags&1)w.u32(ts.externalFileId).u32(ts.externalTilesetId);if(flags&2){const image=doc.images[ts.imageId];assert(image&&image.width===ts.tileWidth&&image.height===ts.tileHeight*ts.tileCount,'Invalid embedded tileset atlas.');const compressed=zlibSync(encodePixels(image,depth,doc.palette,meta.transparentIndex||0));w.u32(compressed.length).raw(compressed);}chunks.push(aseChunk(0x2023,w),...userChunk(ts));if(ts.tileUserData?.length){if(!ts.userData)chunks.push(aseChunk(0x2020,new Writer().u32(0)));for(const ud of ts.tileUserData)chunks.push(...userChunk({userData:ud||{}}));}
 }
 for(const l of layers){const type=l.type==='group'?1:l.type==='tilemap'?2:0;assert(['group','tilemap','reference','image'].includes(l.type),'Unsupported layer type.');const blend=ASEPRITE_BLEND_MODES.indexOf(l.blendMode||'normal');assert(blend>=0,`Unsupported blend mode ${l.blendMode}.`);let level=0,p=l.parentId;while(p){level++;p=layers.find(x=>x.id===p)?.parentId;}let lf=(l.asepriteFlags||0)&~(1|2|64);if(l.visible!==false)lf|=1;if(!l.locked)lf|=2;if(l.type==='reference')lf|=64;const w=new Writer().u16(lf).u16(type).u16(level).u16(0).u16(0).u16(blend).u8(Math.round((l.opacity??1)*255)).zero(3).str(l.name);if(type===2){const index=doc.tilesets.findIndex(t=>t.id===l.tilesetId);assert(index>=0,'Tilemap layer has no tileset.');w.u32(index);}if(hasUuid)w.raw(l.uuid||new Uint8Array(16));chunks.push(aseChunk(0x2004,w),...userChunk(l));}
 }
 const pal=frame.palette;if(fi>0&&pal?.length)chunks.push(paletteChunk(pal,meta.paletteNames));
 if(fi===0){
 if(doc.clips?.length){const w=new Writer().u16(doc.clips.length).zero(8);for(const clip of doc.clips){const indices=clip.frameIds.map(id=>doc.frames.findIndex(f=>f.id===id));assert(indices.length&&indices.every((n,i)=>n>=0&&(i===0||n===indices[i-1]+1)),'Sprite tags require a contiguous forward frame range.');const direction=DIRECTIONS.indexOf(clip.direction||'forward');assert(direction>=0,'Unsupported clip direction.');w.u16(indices[0]).u16(indices.at(-1)).u8(direction).u16(clip.repeat??(clip.loop?0:1)).zero(6).raw(colorRgba(clip.color||'#000000').slice(0,3)).u8(0).str(clip.name);}chunks.push(aseChunk(0x2018,w));if(doc.clips.some(c=>c.userData))for(const clip of doc.clips)chunks.push(...userChunk({userData:clip.userData||{}}));}
 for(const rawSlice of doc.slices||[]){const slice=rawSlice.keys?rawSlice:{...rawSlice,keys:[{frameId:doc.frames[0].id,...rawSlice.bounds,...(rawSlice.pivot?{pivot:rawSlice.pivot}:{}),...(rawSlice.ninePatch?{center:rawSlice.ninePatch}:{})}]};const hasCenter=slice.keys.some(k=>k.center),hasPivot=slice.keys.some(k=>k.pivot),w=new Writer().u32(slice.keys.length).u32((hasCenter?1:0)|(hasPivot?2:0)).u32(0).str(slice.name);for(const key of slice.keys){const index=doc.frames.findIndex(f=>f.id===key.frameId);assert(index>=0,'Slice refers to a missing frame.');w.u32(index).i32(key.x).i32(key.y).u32(key.width).u32(key.height);if(hasCenter){assert(key.center,'All sprite slice keys must share nine-patch fields.');const c=key.center;w.i32(c.x).i32(c.y).u32(c.width).u32(c.height);}if(hasPivot){assert(key.pivot,'All sprite slice keys must share pivot fields.');w.i32(key.pivot.x).i32(key.pivot.y);}}chunks.push(aseChunk(0x2022,w),...userChunk(slice));}
 }
 for(const [li,layer] of layers.entries()){
  const cel=frame.cels[layer.id];if(!cel)continue;assert(layer.type!=='group','Sprite group cannot contain a cel.');assert([cel.x,cel.y,cel.zIndex||0].every(v=>Number.isInteger(v)&&v>=-32768&&v<=32767),'Sprite cel positions and z-index must be signed 16-bit integers.');const image=doc.images[cel.imageId];assert(image,'Cel references a missing image.');assert(image.width<=65535&&image.height<=65535,'Sprite cel dimensions exceed limit.');const key=`${layer.id}\0${cel.imageId}`,linked=seenImages.get(key),type=linked!=null?1:image.tilemap?3:2,w=new Writer().u16(li).i16(cel.x).i16(cel.y).u8(Math.round((cel.opacity??1)*255)).u16(type).i16(cel.zIndex||0).zero(5);
  if(type===1)w.u16(linked);else {seenImages.set(key,fi);w.u16(image.width).u16(image.height);if(type===3){const t=image.tilemap;assert([8,16,32].includes(t.bitsPerTile),'Invalid tile bits.');assert(t.tiles.length===image.width*image.height,'Tilemap cell count mismatch.');w.u16(t.bitsPerTile).u32(t.idMask).u32(t.xFlipMask).u32(t.yFlipMask).u32(t.diagonalFlipMask).zero(10);const tw=new Writer();for(const value of t.tiles){if(t.bitsPerTile===32)tw.u32(value);else if(t.bitsPerTile===16)tw.u16(value);else tw.u8(value);}w.raw(zlibSync(tw.done()));}else w.raw(zlibSync(encodePixels(image,depth,frame.palette||doc.palette,meta.transparentIndex||0)));}
  chunks.push(aseChunk(0x2005,w));if(cel.preciseBounds){const b=cel.preciseBounds;chunks.push(aseChunk(0x2006,new Writer().u32(b.flags??1).i32(Math.round(b.x*65536)).i32(Math.round(b.y*65536)).i32(Math.round(b.width*65536)).i32(Math.round(b.height*65536)).zero(16)));}chunks.push(...userChunk(cel));
 }
 const body=concat(chunks),fw=new Writer().u32(body.length+16).u16(0xf1fa).u16(Math.min(chunks.length,65535)).u16(frame.durationMs).zero(2).u32(chunks.length).raw(body);frames.push(fw.done());
 }
 const body=concat(frames),header=new Writer().u32(body.length+128).u16(0xa5e0).u16(doc.frames.length).u16(doc.width).u16(doc.height).u16(depth).u32(3|(hasUuid?4:0)).u16(doc.frames[0].durationMs).zero(8).u8(meta.transparentIndex||0).zero(3).u16(doc.palette?.length||0).u8(meta.pixelRatio?.width||1).u8(meta.pixelRatio?.height||1).i16(meta.grid?.x||0).i16(meta.grid?.y||0).u16(meta.grid?.width||0).u16(meta.grid?.height||0).zero(84);return concat([header.done(),body]);
}

const crcTable=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc32(data){let c=0xffffffff;for(const b of data)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function be32(n){return Uint8Array.of(n>>>24,n>>>16,n>>>8,n);}
function pngChunk(name,payload){const type=encoder.encode(name),body=concat([type,payload]);return concat([be32(payload.length),body,be32(crc32(body))]);}
export function writePng(width,height,rgba,options={}){dimensions(width,height);assert(rgba.length===width*height*4,'PNG RGBA data length mismatch.');const head=concat([be32(width),be32(height),Uint8Array.of(8,6,0,0,0)]),scan=new Uint8Array(height*(width*4+1));for(let y=0;y<height;y++)scan.set(rgba.subarray(y*width*4,(y+1)*width*4),y*(width*4+1)+1);return concat([Uint8Array.of(137,80,78,71,13,10,26,10),pngChunk('IHDR',head),...(options.colorProfile?.type===2?[pngChunk('iCCP',concat([encoder.encode('PixelWall ICC'),Uint8Array.of(0,0),zlibSync(Uint8Array.from(options.colorProfile.icc))]))]:[pngChunk('sRGB',Uint8Array.of(0))]),pngChunk('IDAT',zlibSync(scan)),pngChunk('IEND',new Uint8Array())]);}
function paeth(a,b,c){const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;}
export function readPng(input){
 const data=bytes(input);assert(data.length>=33&&[137,80,78,71,13,10,26,10].every((b,i)=>data[i]===b),'Not a PNG image.');const v=new DataView(data.buffer,data.byteOffset,data.byteLength),idat=[],warnings=[];let p=8,width,height,bitDepth,colorType,interlace,palette=null,transparency=null,ended=false,header=false,colorProfile=null,pngGamma=null,explicitSRGB=false;
 while(p<data.length){assert(p+12<=data.length,'Truncated PNG chunk.');const len=v.getUint32(p),type=decoder.decode(data.subarray(p+4,p+8));assert(p+len+12<=data.length,'Truncated PNG payload.');const body=data.subarray(p+8,p+8+len);assert(crc32(data.subarray(p+4,p+8+len))===v.getUint32(p+8+len),`PNG ${type} checksum mismatch.`);
 if(type==='IHDR'){assert(!header&&p===8&&len===13,'Invalid PNG header.');header=true;width=v.getUint32(p+8);height=v.getUint32(p+12);dimensions(width,height);bitDepth=body[8];colorType=body[9];assert(body[10]===0&&body[11]===0&&body[12]<=1,'Unsupported PNG compression, filter or interlace.');interlace=body[12];assert(({0:[1,2,4,8,16],2:[8,16],3:[1,2,4,8],4:[8,16],6:[8,16]})[colorType]?.includes(bitDepth),'Unsupported PNG color type/bit depth.');}
 else if(type==='PLTE'){assert(len%3===0&&len>0&&len<=768,'Invalid PNG palette.');palette=body;}
 else if(type==='tRNS')transparency=body;
 else if(type==='IDAT')idat.push(body);
 else if(type==='IEND'){ended=true;p+=12;break;}
 else if(type==='acTL')throw new Error('Animated PNG is not supported; import PNG frames or a GIF instead.');
 else if(type==='sRGB'){assert(len===1&&body[0]<=3,'Invalid PNG rendering intent.');explicitSRGB=true;}
 else if(type==='gAMA'){assert(len===4,'Invalid PNG gamma.');const value=new DataView(body.buffer,body.byteOffset,body.byteLength).getUint32(0);assert(value>0,'Invalid PNG gamma.');pngGamma=100000/value;}
 else if(type==='iCCP'){const end=body.indexOf(0);assert(end>0&&end<=79&&body[end+1]===0,'Invalid PNG ICC profile.');const compressed=body.subarray(end+2),icc=unzlibSync(compressed,{out:new Uint8Array(4*1024*1024+1)});assert(icc.length>=132&&icc.length<=4*1024*1024,'PNG ICC profile exceeds 4 MB or is truncated.');inflateExact(compressed,icc.length);colorProfile={type:2,flags:0,gamma:0,icc:Array.from(icc)};}
 else if(type[0]===type[0].toUpperCase())throw new Error(`Unsupported critical PNG chunk ${type}.`);
 p+=len+12;
 }
 assert(header&&ended&&idat.length,'Incomplete PNG file.');assert(p===data.length,'Unexpected bytes after PNG end.');if(colorType===3)assert(palette,'Indexed PNG is missing its palette.');if(bitDepth===16)warnings.push('16-bit PNG channels are reduced to 8 bits for pixel editing.');
 const channels={0:1,2:3,3:1,4:2,6:4}[colorType],passes=interlace?[[0,0,8,8],[4,0,8,8],[0,4,4,8],[2,0,4,4],[0,2,2,4],[1,0,2,2],[0,1,1,2]]:[[0,0,1,1]],scanLen=passes.reduce((n,[x,y,dx,dy])=>{const w=Math.ceil((width-x)/dx),h=Math.ceil((height-y)/dy);return n+(w>0&&h>0?(1+Math.ceil(w*channels*bitDepth/8))*h:0);},0),raw=inflateExact(concat(idat),scanLen),rgba=new Uint8Array(width*height*4);let offset=0;
 for(const [x0,y0,dx,dy] of passes){const w=Math.ceil((width-x0)/dx),h=Math.ceil((height-y0)/dy);if(w<=0||h<=0)continue;const rowBytes=Math.ceil(w*channels*bitDepth/8),bpp=Math.max(1,Math.ceil(channels*bitDepth/8));let prev=new Uint8Array(rowBytes);
 for(let y=0;y<h;y++){const filter=raw[offset++];assert(filter<=4,'Invalid PNG filter.');const row=raw.slice(offset,offset+rowBytes);offset+=rowBytes;for(let i=0;i<rowBytes;i++){const a=i>=bpp?row[i-bpp]:0,b=prev[i],c=i>=bpp?prev[i-bpp]:0;row[i]=(row[i]+(filter===1?a:filter===2?b:filter===3?Math.floor((a+b)/2):filter===4?paeth(a,b,c):0))&255;}
 const sample=(i)=>bitDepth===16?(row[i*2]<<8)|row[i*2+1]:bitDepth===8?row[i]:(row[Math.floor(i*bitDepth/8)]>>>(8-bitDepth-(i*bitDepth)%8))&((1<<bitDepth)-1),to8=(n)=>Math.round(n*255/(bitDepth===16?65535:(1<<bitDepth)-1));
 for(let x=0;x<w;x++){const q=x*channels,out=((y0+y*dy)*width+x0+x*dx)*4;let r,g,b,a=255;if(colorType===3){const index=sample(q);assert(index*3+2<palette.length,'PNG pixel references a missing palette color.');r=palette[index*3];g=palette[index*3+1];b=palette[index*3+2];a=transparency?.[index]??255;}else if(colorType===0||colorType===4){const gray=sample(q);r=g=b=to8(gray);a=colorType===4?to8(sample(q+1)):transparency&&gray===((transparency[0]<<8)|transparency[1])?0:255;}else{const rv=sample(q),gv=sample(q+1),bv=sample(q+2);r=to8(rv);g=to8(gv);b=to8(bv);a=colorType===6?to8(sample(q+3)):transparency&&rv===((transparency[0]<<8)|transparency[1])&&gv===((transparency[2]<<8)|transparency[3])&&bv===((transparency[4]<<8)|transparency[5])?0:255;}rgba.set([r,g,b,a],out);}prev=row;
 }}return {width,height,rgba,warnings:[...new Set(warnings)],...(colorProfile?{colorProfile}:!explicitSRGB&&pngGamma?{colorProfile:{type:1,flags:1,gamma:pngGamma}}:{})};
}
export function importGif(input,options={}){
 const data=bytes(input);assert(data.length>=13&&/^GIF8[79]a$/.test(decoder.decode(data.subarray(0,6))),'Not a GIF image.');const reader=new GifReader(data),{width,height}=reader;dimensions(width,height);const entries=[],canvas=new Uint8Array(width*height*4),warnings=['GIF imports use its indexed colors and frame timing; GIF has binary transparency.'];assert(reader.numFrames()>0,'GIF has no frames.');assert(width*height*reader.numFrames()<=MAX_PIXELS,'GIF animation exceeds the import pixel limit.');let previous=null,restore=null;
 const hasGlobalPalette=!!(data[10]&0x80),backgroundIndex=data[11],bgOffset=13+backgroundIndex*3;const bg=hasGlobalPalette&&bgOffset+2<data.length?[data[bgOffset],data[bgOffset+1],data[bgOffset+2],255]:[0,0,0,0];
 for(let i=0;i<reader.numFrames();i++){
  const info=reader.frameInfo(i);
  if(previous?.disposal===2){const fill=previous.transparent_index!=null?[0,0,0,0]:bg;for(let y=previous.y;y<previous.y+previous.height;y++)for(let x=previous.x;x<previous.x+previous.width;x++)canvas.set(fill,(y*width+x)*4);}
  else if(previous?.disposal===3&&restore)canvas.set(restore);
  if(i===0&&info.transparent_index==null)for(let p=0;p<canvas.length;p+=4)canvas.set(bg,p);
  restore=info.disposal===3?canvas.slice():null;const decoded=new Uint8Array(canvas.length);reader.decodeAndBlitFrameRGBA(i,decoded);for(let p=0;p<decoded.length;p+=4)if(decoded[p+3])canvas.set(decoded.subarray(p,p+4),p);
  entries.push({width,height,rgba:canvas.slice(),durationMs:info.delay?info.delay*10:100});previous=info;
 }
 const document=imageDocument(entries,{...options,name:options.name||'Imported GIF'});document.metadata.gif={loopCount:reader.loopCount()};return {document,warnings};
}
export function importSheet(image,options={}){
 const {width,height,rgba}=image;dimensions(width,height);assert(rgba.length===width*height*4,'Sprite sheet pixels mismatch.');const cellWidth=Number(options.frameWidth||options.cellWidth),cellHeight=Number(options.frameHeight||options.cellHeight),margin=Number(options.margin??options.padding??0),spacing=Number(options.spacing||0);dimensions(cellWidth,cellHeight);assert([margin,spacing].every(n=>Number.isInteger(n)&&n>=0),'Sheet margin and spacing must be nonnegative integers.');const availableColumns=Math.floor((width-margin*2+spacing)/(cellWidth+spacing)),columns=options.columns||availableColumns,rows=Math.floor((height-margin*2+spacing)/(cellHeight+spacing));assert(Number.isInteger(columns)&&columns>0&&columns<=availableColumns&&rows>0,'Frame dimensions do not fit the sheet.');const count=options.count??columns*rows;assert(Number.isInteger(count)&&count>0&&count<=columns*rows,'Requested sheet frame count exceeds available cells.');const entries=[];
 for(let i=0;i<count;i++){const col=options.order==='column'?Math.floor(i/rows):i%columns,row=options.order==='column'?i%rows:Math.floor(i/columns),x=margin+col*(cellWidth+spacing),y=margin+row*(cellHeight+spacing),out=new Uint8Array(cellWidth*cellHeight*4);for(let yy=0;yy<cellHeight;yy++)out.set(rgba.subarray(((y+yy)*width+x)*4,((y+yy)*width+x+cellWidth)*4),yy*cellWidth*4);entries.push({width:cellWidth,height:cellHeight,rgba:out});}
 return imageDocument(entries,options);
}
function frameBounds(entry,trim){let x=0,y=0,w=entry.width,h=entry.height;if(trim){let x1=w,y1=h,x2=-1,y2=-1;for(let py=0;py<h;py++)for(let px=0;px<w;px++)if(entry.rgba[(py*w+px)*4+3]){x1=Math.min(x1,px);y1=Math.min(y1,py);x2=Math.max(x2,px);y2=Math.max(y2,py);}if(x2<0)return {x:0,y:0,w:1,h:1,empty:true};x=x1;y=y1;w=x2-x1+1;h=y2-y1+1;}return{x,y,w,h,empty:false};}
const pow2=n=>2**Math.ceil(Math.log2(Math.max(1,n)));
function intersects(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
function maxRects(items,width,height){let free=[{x:0,y:0,w:width,h:height}];const placed=[];for(const item of items){let best=null;for(const f of free)if(item.w<=f.w&&item.h<=f.h){const score=[Math.min(f.w-item.w,f.h-item.h),Math.max(f.w-item.w,f.h-item.h),f.y,f.x];if(!best||score.some((v,i)=>v<best.score[i]&&score.slice(0,i).every((n,j)=>n===best.score[j])))best={x:f.x,y:f.y,w:item.w,h:item.h,score};}if(!best)return null;const next=[];for(const f of free){if(!intersects(f,best)){next.push(f);continue;}if(best.x>f.x)next.push({x:f.x,y:f.y,w:best.x-f.x,h:f.h});if(best.x+best.w<f.x+f.w)next.push({x:best.x+best.w,y:f.y,w:f.x+f.w-best.x-best.w,h:f.h});if(best.y>f.y)next.push({x:f.x,y:f.y,w:f.w,h:best.y-f.y});if(best.y+best.h<f.y+f.h)next.push({x:f.x,y:best.y+best.h,w:f.w,h:f.y+f.h-best.y-best.h});}free=next.filter((a,i)=>!next.some((b,j)=>i!==j&&a.x>=b.x&&a.y>=b.y&&a.x+a.w<=b.x+b.w&&a.y+a.h<=b.y+b.h&&(a.w!==b.w||a.h!==b.h||i>j)));placed.push({...item,x:best.x,y:best.y});}return placed;}
function blitTrim(atlas,atlasWidth,entry,bounds,x,y,extrude){for(let py=-extrude;py<bounds.h+extrude;py++)for(let px=-extrude;px<bounds.w+extrude;px++){const sx=bounds.x+Math.min(bounds.w-1,Math.max(0,px)),sy=bounds.y+Math.min(bounds.h-1,Math.max(0,py)),source=(sy*entry.width+sx)*4,dest=((y+py)*atlasWidth+x+px)*4;if(!bounds.empty)atlas.set(entry.rgba.subarray(source,source+4),dest);}}
export function packAtlas(entries,options={}){
 assert(entries.length>0,'No frames to pack.');const padding=options.padding??1,extrude=options.extrude??0,maxSize=options.maxSize??8192,border=options.border??padding;assert([padding,extrude,border].every(n=>Number.isInteger(n)&&n>=0),'Atlas spacing must be nonnegative integers.');assert(Number.isInteger(maxSize)&&maxSize>0&&maxSize<=16384,'Atlas maxSize must be 1–16384.');const names=new Set(),items=entries.map((entry,index)=>{dimensions(entry.width,entry.height);assert(entry.rgba.length===entry.width*entry.height*4,'Atlas frame pixels mismatch.');const name=entry.name||entry.id||`frame-${index+1}`;assert(!names.has(name),'Atlas frame names must be unique.');names.add(name);const bounds=frameBounds(entry,options.trim!==false);return{index,name,entry,bounds,w:bounds.w+extrude*2+padding,h:bounds.h+extrude*2+padding};}).sort((a,b)=>Math.max(b.w,b.h)-Math.max(a.w,a.h)||b.w*b.h-a.w*a.h||a.index-b.index);
 const layout=options.layout||'packed';assert(['packed','horizontal','vertical','grid'].includes(layout),'Unknown atlas layout.');let placed,width,height;
 if(layout!=='packed'){
  const ordered=[...items].sort((a,b)=>a.index-b.index),columns=layout==='horizontal'?items.length:layout==='vertical'?1:options.columns||Math.ceil(Math.sqrt(items.length));assert(Number.isInteger(columns)&&columns>0,'Atlas columns must be positive.');const cw=Math.max(...items.map(i=>i.w)),ch=Math.max(...items.map(i=>i.h));placed=ordered.map((item,index)=>({...item,x:(index%columns)*cw,y:Math.floor(index/columns)*ch}));width=columns*cw+border*2;height=Math.ceil(items.length/columns)*ch+border*2;if(options.powerOfTwo){width=pow2(width);height=pow2(height);}assert(width<=maxSize&&height<=maxSize,'Layout exceeds the maximum atlas size.');
 }else{
 const minW=Math.max(...items.map(i=>i.w))+border*2,minH=Math.max(...items.map(i=>i.h))+border*2,area=items.reduce((n,i)=>n+i.w*i.h,0),candidates=[];
 assert(!!options.width===!!options.height,'Specify both atlas width and height.');
 if(options.width&&options.height)candidates.push([options.width,options.height]);else {const ws=[],hs=[];for(let w=pow2(minW);w<=maxSize;w*=2)ws.push(w);for(let h=pow2(minH);h<=maxSize;h*=2)hs.push(h);if(!options.powerOfTwo){if(!ws.includes(maxSize))ws.push(maxSize);if(!hs.includes(maxSize))hs.push(maxSize);}for(const w of ws)for(const h of hs)if((w-border*2)*(h-border*2)>=area)candidates.push([w,h]);}candidates.sort((a,b)=>a[0]*a[1]-b[0]*b[1]||Math.abs(a[0]-a[1])-Math.abs(b[0]-b[1]));
 for(const [w,h] of candidates){if(w>maxSize||h>maxSize||w<=border*2||h<=border*2)continue;const result=maxRects(items,w-border*2,h-border*2);if(result){placed=result;width=w;height=h;break;}}assert(placed,'Frames do not fit the maximum atlas size; increase maxSize or export fewer frames.');if(!options.powerOfTwo&&!options.width&&!options.height){width=Math.max(...placed.map(i=>i.x+i.w))+border*2;height=Math.max(...placed.map(i=>i.y+i.h))+border*2;}
 }
 dimensions(width,height);const rgba=new Uint8Array(width*height*4),frames=[];
 for(const item of placed){const x=item.x+border+extrude,y=item.y+border+extrude;blitTrim(rgba,width,item.entry,item.bounds,x,y,extrude);frames.push({filename:item.name,id:item.entry.id||item.name,frame:{x,y,w:item.bounds.w,h:item.bounds.h},rotated:false,trimmed:item.bounds.w!==item.entry.width||item.bounds.h!==item.entry.height||item.bounds.x!==0||item.bounds.y!==0,spriteSourceSize:{x:item.bounds.x,y:item.bounds.y,w:item.bounds.w,h:item.bounds.h},sourceSize:{w:item.entry.width,h:item.entry.height},duration:item.entry.durationMs||100,empty:item.bounds.empty,pivot:item.entry.pivot||{x:0.5,y:0.5},index:item.index});}frames.sort((a,b)=>a.index-b.index);
 const scale=options.scale??1;assert(Number.isFinite(Number(scale))&&Number(scale)>0,'Atlas metadata scale must be positive.');const scaleBounds=value=>value?Object.fromEntries(Object.entries(value).map(([key,v])=>[key,['x','y','width','height'].includes(key)&&typeof v==='number'?v*Number(scale):v])):value;
 const slices=(options.slices||[]).map(slice=>({...slice,...(slice.bounds?{bounds:scaleBounds(slice.bounds)}:{}),...(slice.pivot?{pivot:scaleBounds(slice.pivot)}:{}),...(slice.ninePatch?{ninePatch:scaleBounds(slice.ninePatch)}:{}),...(slice.keys?{keys:slice.keys.map(key=>({...scaleBounds(key),...(key.pivot?{pivot:scaleBounds(key.pivot)}:{}),...(key.center?{center:scaleBounds(key.center)}:{})}))}:{})}));
 const frameTags=(options.clips||[]).flatMap(clip=>{const indices=entries.map((entry,index)=>clip.frameIds?.includes(entry.id)?index:-1).filter(index=>index>=0);return indices.length?[{...clip,from:indices[0],to:indices.at(-1),frameIndices:indices,sourceFrameIds:clip.frameIds,frameIds:indices.map(i=>entries[i].id),partial:clip.frameIds.some(id=>!entries.some(e=>e.id===id))}]:[];});
 return {width,height,rgba,frames,meta:{app:'PixelWall',version:'4',image:options.imageName||'atlas.png',format:'RGBA8888',size:{w:width,h:height},scale:String(scale),padding,extrude,border,layout,powerOfTwo:!!options.powerOfTwo,frameTags,sourceClips:options.clips||[],slices,sourceSlices:options.slices||[]}};
}
export function makeSpriteSheet(entries,options={}){assert(entries.length>0,'No frames to export.');const cellWidth=Math.max(...entries.map(e=>e.width)),cellHeight=Math.max(...entries.map(e=>e.height)),columns=options.columns||entries.length,padding=options.padding||0;assert(Number.isInteger(columns)&&columns>0&&Number.isInteger(padding)&&padding>=0,'Invalid sheet columns/padding.');const rows=Math.ceil(entries.length/columns),width=columns*cellWidth+(columns-1)*padding,height=rows*cellHeight+(rows-1)*padding;dimensions(width,height);const rgba=new Uint8Array(width*height*4),frames=[];entries.forEach((entry,i)=>{const x=i%columns*(cellWidth+padding),y=Math.floor(i/columns)*(cellHeight+padding);blitTrim(rgba,width,entry,{x:0,y:0,w:entry.width,h:entry.height},x,y,0);frames.push({filename:entry.name||`frame-${i+1}`,frame:{x,y,w:entry.width,h:entry.height},duration:entry.durationMs||100});});return {width,height,rgba,frames,meta:{app:'PixelWall',size:{w:width,h:height},columns,rows,padding}};}
export function encodeGif(entries,options={}){
 assert(entries.length>0,'No GIF frames.');const {width,height}=entries[0];dimensions(width,height);assert(width<=65535&&height<=65535,'GIF dimensions exceed limit.');assert(entries.every(e=>e.width===width&&e.height===height),'GIF frames must share dimensions.');const buffer=new Uint8Array(Math.max(4096,width*height*entries.length*2+entries.length*1024)),writer=new GifWriter(buffer,width,height,options.loop===-1?{}:{loop:options.loop??0});
 for(const entry of entries){const exact=new Map(),pixels=entry.rgba;assert(pixels.length===width*height*4,'GIF pixel count mismatch.');for(let p=0;p<pixels.length;p+=4)if(pixels[p+3]>=128){const value=pixels[p]*65536+pixels[p+1]*256+pixels[p+2];if(!exact.has(value))exact.set(value,exact.size+1);if(exact.size>255)break;}let palette=[0],indices=new Uint8Array(width*height);if(exact.size<=255){palette.push(...exact.keys());for(let i=0;i<indices.length;i++){const p=i*4;indices[i]=pixels[p+3]>=128?exact.get(pixels[p]*65536+pixels[p+1]*256+pixels[p+2]):0;}}else{for(let r=0;r<6;r++)for(let g=0;g<6;g++)for(let b=0;b<6;b++)palette.push(r*51*65536+g*51*256+b*51);for(let i=0;i<indices.length;i++){const p=i*4;indices[i]=pixels[p+3]>=128?1+Math.round(pixels[p]/51)*36+Math.round(pixels[p+1]/51)*6+Math.round(pixels[p+2]/51):0;}}while(palette.length<pow2(palette.length))palette.push(0);if(palette.length<2)palette.push(0);writer.addFrame(0,0,width,height,indices,{palette,transparent:0,disposal:2,delay:Math.max(1,Math.min(65535,Math.round((entry.durationMs||100)/10)))});}
 return buffer.slice(0,writer.end());
}
export function makeSequenceZip(entries,options={}){const files={};entries.forEach((e,i)=>{const name=(e.name||`frame-${String(i+1).padStart(4,'0')}`).replace(/[^a-z0-9_.-]/gi,'_');assert(!files[`${name}.png`],'Duplicate ZIP frame filename.');files[`${name}.png`]=writePng(e.width,e.height,e.rgba);});files['metadata.json']=strToU8(JSON.stringify({app:'PixelWall',frames:entries.map((e,i)=>({index:i,name:e.name||`frame-${String(i+1).padStart(4,'0')}`,durationMs:e.durationMs||100})),clips:options.clips||[],slices:options.slices||[]},null,2));return zipSync(files);}

/** Windows BMP: RGB, indexed, bitfields and RLE4/RLE8. */
export function readBmp(input){
 const data=bytes(input),r=new Reader(data);assert(data.length>=26&&r.u16()===0x4d42,'Not a BMP image.');const fileSize=r.u32();r.skip(4);const pixelOffset=r.u32(),headerSize=r.u32();assert(fileSize===0||fileSize<=data.length,'Truncated BMP file.');assert(headerSize===12||[40,52,56,108,124].includes(headerSize),'Unsupported BMP header version.');assert(14+headerSize<=data.length&&pixelOffset>=14+headerSize&&pixelOffset<=data.length,'Invalid BMP pixel offset.');let width,height,topDown=false,bits,compression=0,colorCount=0;const warnings=[];let maskR=0,maskG=0,maskB=0,maskA=0;
 if(headerSize===12){width=r.u16();height=r.u16();assert(r.u16()===1,'Invalid BMP planes.');bits=r.u16();}else{width=r.i32();const signedHeight=r.i32();topDown=signedHeight<0;height=Math.abs(signedHeight);assert(r.u16()===1,'Invalid BMP planes.');bits=r.u16();compression=r.u32();r.skip(12);colorCount=r.u32();r.skip(4);if(headerSize>=52){maskR=r.u32();maskG=r.u32();maskB=r.u32();if(headerSize>=56)maskA=r.u32();}if(headerSize>=108){r.p=14+56;const space=r.u32();if(![0x73524742,0x57696e20].includes(space))warnings.push('BMP calibrated or embedded color profile is not converted; imported pixels use sRGB.');}}
 dimensions(width,height);assert([1,4,8,16,24,32].includes(bits),'Unsupported BMP bit depth.');assert([0,1,2,3,6].includes(compression),'Unsupported BMP compression (JPEG/PNG-embedded BMP is not supported).');assert(compression!==1||bits===8,'BMP RLE8 requires 8-bit pixels.');assert(compression!==2||bits===4,'BMP RLE4 requires 4-bit pixels.');assert(![3,6].includes(compression)||[16,32].includes(bits),'BMP bitfields require 16 or 32 bits.');assert(!topDown||[0,3,6].includes(compression),'Top-down RLE BMP is invalid.');r.p=14+headerSize;
 if([3,6].includes(compression)&&headerSize===40){maskR=r.u32();maskG=r.u32();maskB=r.u32();if(compression===6)maskA=r.u32();}
 if(![3,6].includes(compression)){if(bits===16){maskR=0x7c00;maskG=0x03e0;maskB=0x001f;maskA=0;}else if(bits===32){maskR=0x00ff0000;maskG=0x0000ff00;maskB=0x000000ff;maskA=0;}}
 function channel(value,mask,defaultValue=0){if(!mask)return defaultValue;mask>>>=0;let shift=0;while(((mask>>>shift)&1)===0&&shift<32)shift++;const max=mask>>>shift;assert((max&(max+1))===0,'Noncontiguous BMP channel mask.');return Math.round(((value&mask)>>>0)/2**shift*255/max);}
 if([16,32].includes(bits))assert(maskR&&maskG&&maskB&&!(maskR&maskG)&&!(maskR&maskB)&&!(maskG&maskB)&&!(maskA&(maskR|maskG|maskB)),'Invalid overlapping BMP bit masks.');
 const palette=[];if(bits<=8){const count=colorCount||2**bits;assert(count<=2**bits,'BMP palette exceeds bit depth.');for(let i=0;i<count;i++){const b=r.u8(),g=r.u8(),red=r.u8();if(headerSize!==12)r.skip(1);palette.push([red,g,b,255]);}assert(r.p<=pixelOffset,'BMP palette overlaps pixels.');}
 const rgba=new Uint8Array(width*height*4),put=(x,y,index)=>{assert(x>=0&&x<width&&y>=0&&y<height,'BMP RLE coordinates exceed the image.');assert(palette[index],'BMP index refers to a missing palette color.');rgba.set(palette[index],((topDown?y:height-1-y)*width+x)*4);};
 r.p=pixelOffset;if(compression===1||compression===2){for(let y=0;y<height;y++)for(let x=0;x<width;x++)put(x,y,0);let x=0,y=0,ended=false;while(r.p<data.length&&!ended){const count=r.u8(),value=r.u8();if(count){for(let i=0;i<count;i++)put(x++,y,compression===1?value:i%2?value&15:value>>>4);}else if(value===0){x=0;y++;}else if(value===1)ended=true;else if(value===2){x+=r.u8();y+=r.u8();assert(x<=width&&y<height,'BMP RLE delta exceeds image.');}else{const n=value,byteCount=compression===1?n:Math.ceil(n/2),packet=r.take(byteCount);for(let i=0;i<n;i++)put(x++,y,compression===1?packet[i]:i%2?packet[i>>1]&15:packet[i>>1]>>>4);if(byteCount%2)r.skip(1);}}assert(ended,'BMP RLE has no end-of-bitmap marker.');}
 else {const stride=Math.ceil(width*bits/32)*4;assert(pixelOffset+stride*height<=data.length,'Truncated BMP raster.');for(let y=0;y<height;y++)for(let x=0;x<width;x++){const p=pixelOffset+y*stride+Math.floor(x*bits/8),out=((topDown?y:height-1-y)*width+x)*4;let color;if(bits<=8){const index=bits===8?data[p]:bits===4?x%2?data[p]&15:data[p]>>>4:(data[p]>>>(7-x%8))&1;assert(palette[index],'BMP index refers to a missing palette color.');color=palette[index];}else if(bits===24)color=[data[p+2],data[p+1],data[p],255];else{const value=bits===16?data[p]|data[p+1]<<8:(data[p]|data[p+1]<<8|data[p+2]<<16|data[p+3]<<24)>>>0;color=[channel(value,maskR),channel(value,maskG),channel(value,maskB),channel(value,maskA,255)];}rgba.set(color,out);}}
 return {width,height,rgba,warnings};
}
/** Emits a BITMAPV5HEADER with explicit RGBA masks and sRGB color space. */
export function writeBmp(width,height,rgba){dimensions(width,height);assert(rgba.length===width*height*4,'BMP pixel data length mismatch.');const offset=14+124,header=new Writer().u16(0x4d42).u32(offset+rgba.length).zero(4).u32(offset).u32(124).i32(width).i32(-height).u16(1).u16(32).u32(3).u32(rgba.length).i32(2835).i32(2835).u32(0).u32(0).u32(0x00ff0000).u32(0x0000ff00).u32(0x000000ff).u32(0xff000000).u32(0x73524742).zero(36).zero(12).u32(4).zero(12);const raster=new Uint8Array(rgba.length);for(let i=0;i<rgba.length;i+=4)raster.set([rgba[i+2],rgba[i+1],rgba[i],rgba[i+3]],i);return concat([header.done(),raster]);}
/** Truevision TGA v1/v2: indexed, truecolor and gray, raw or RLE. */
export function readTga(input){
 const data=bytes(input),r=new Reader(data);assert(data.length>=18,'TGA header is truncated.');const idLength=r.u8(),colorMapType=r.u8(),type=r.u8(),mapFirst=r.u16(),mapLength=r.u16(),mapBits=r.u8(),xOrigin=r.u16(),yOrigin=r.u16(),width=r.u16(),height=r.u16(),bits=r.u8(),descriptor=r.u8();dimensions(width,height);assert([1,2,3,9,10,11].includes(type)&&colorMapType<=1,'Unsupported TGA image type.');assert((descriptor&0xc0)===0,'Interleaved TGA images are unsupported.');const indexed=type===1||type===9,gray=type===3||type===11,rle=type>=9;assert(!indexed||colorMapType===1,'Indexed TGA requires a color map.');assert(indexed?[8,16].includes(bits):gray?[8,16].includes(bits):[15,16,24,32].includes(bits),'Unsupported TGA pixel depth.');r.skip(idLength);const warnings=[];let attributeType=null,footerStart=data.length;
 if(data.length>=26&&decoder.decode(data.subarray(data.length-18,data.length-1))==='TRUEVISION-XFILE.'){
  footerStart=data.length-26;const footer=new Reader(data.subarray(footerStart)),extensionOffset=footer.u32(),developerOffset=footer.u32();if(extensionOffset){assert(extensionOffset+495<=footerStart,'Truncated TGA extension.');attributeType=data[extensionOffset+494];if(data[extensionOffset+478]||data[extensionOffset+479]||data[extensionOffset+480]||data[extensionOffset+481])warnings.push('TGA gamma metadata is not converted; imported pixels use sRGB.');if(data.subarray(extensionOffset+2,extensionOffset+494).some(v=>v!==0))warnings.push('TGA extension metadata is not retained in the raster project.');}if(developerOffset)warnings.push('TGA developer metadata is not retained in the raster project.');
 }
 const alphaBits=descriptor&15;function readColor(depth,isGray=false,fromPalette=false){if(isGray){const v=r.u8();return[v,v,v,depth===16?r.u8():255];}if(depth===15||depth===16){const v=r.u16();return[Math.round(((v>>10)&31)*255/31),Math.round(((v>>5)&31)*255/31),Math.round((v&31)*255/31),depth===16&&(alphaBits||fromPalette)?(v&0x8000?255:0):255];}const b=r.u8(),g=r.u8(),red=r.u8(),a=depth===32?r.u8():255;return[red,g,b,depth===32&&(fromPalette||alphaBits>0||attributeType===3||attributeType===4)?a:255];}
 const palette=[];if(colorMapType===1){assert([15,16,24,32].includes(mapBits),'Unsupported TGA palette entry depth.');for(let i=0;i<mapLength;i++)palette[mapFirst+i]=readColor(mapBits,false,true);}
 const readPixel=()=>{if(indexed){const index=bits===8?r.u8():r.u16();assert(palette[index],'TGA pixel references a missing palette color.');return palette[index];}return readColor(bits,gray);},rgba=new Uint8Array(width*height*4);let written=0;
 const put=color=>{assert(written<width*height,'TGA RLE packet exceeds image size.');let x=written%width,y=Math.floor(written/width);if(descriptor&16)x=width-1-x;if(!(descriptor&32))y=height-1-y;let [red,g,b,a]=color;if(attributeType===0||attributeType===1)a=255;else if(attributeType===4&&a>0){red=Math.min(255,Math.round(red*255/a));g=Math.min(255,Math.round(g*255/a));b=Math.min(255,Math.round(b*255/a));}rgba.set([red,g,b,a],(y*width+x)*4);written++;};
 while(written<width*height){if(!rle){put(readPixel());continue;}const packet=r.u8(),count=(packet&127)+1;assert(written+count<=width*height,'TGA RLE packet exceeds dimensions.');if(packet&128){const color=readPixel();for(let i=0;i<count;i++)put(color);}else for(let i=0;i<count;i++)put(readPixel());}assert(r.p<=footerStart,'TGA pixels overlap its footer.');if(xOrigin||yOrigin)warnings.push(`TGA origin (${xOrigin}, ${yOrigin}) is not applied to the raster canvas.`);return {width,height,rgba,warnings:[...new Set(warnings)]};
}
/** Top-left BGRA TGA v2 with straight alpha. */
export function writeTga(width,height,rgba,options={}){
 dimensions(width,height);assert(width<=65535&&height<=65535&&rgba.length===width*height*4,'TGA dimensions or pixels are invalid.');const useRle=options.rle!==false,w=new Writer().u8(0).u8(0).u8(useRle?10:2).zero(9).u16(width).u16(height).u8(32).u8(0x28),put=i=>w.raw([rgba[i*4+2],rgba[i*4+1],rgba[i*4],rgba[i*4+3]]),equal=(a,b)=>rgba[a*4]===rgba[b*4]&&rgba[a*4+1]===rgba[b*4+1]&&rgba[a*4+2]===rgba[b*4+2]&&rgba[a*4+3]===rgba[b*4+3];
 if(!useRle)for(let i=0;i<width*height;i++)put(i);else for(let y=0;y<height;y++){let i=y*width,end=i+width;while(i<end){let run=1;while(i+run<end&&run<128&&equal(i,i+run))run++;if(run>1){w.u8(0x80|run-1);put(i);i+=run;}else{const start=i++;while(i<end&&i-start<128&&!(i+1<end&&equal(i,i+1)))i++;w.u8(i-start-1);for(let j=start;j<i;j++)put(j);}}}
 const body=w.done(),extension=new Writer().u16(495).zero(492).u8(3).done(),footer=new Writer().u32(body.length).u32(0).raw(encoder.encode('TRUEVISION-XFILE.')).u8(0).done();return concat([body,extension,footer]);
}

/** Game-ready PNG assets, metadata, native project and per-frame Tiled maps.
 * The caller MUST authorize Pro before invoking this function. Pass colorManager
 * for custom profiles. Supplied entries/atlas must already contain sRGB pixels.
 * Pass projectDocument when doc is a visibility-filtered rendering scope, so
 * the embedded native project preserves the complete original artwork. */
export function makeGamePackage(doc,options={}){
 const projectDocument=options.projectDocument??doc;
 const safe=value=>String(value||'asset').replace(/[^a-z0-9_.-]/gi,'_'),json=value=>strToU8(JSON.stringify(value,null,2)),entries=options.entries||doc.frames.map((f,i)=>({id:f.id,name:`${safe(doc.name)}-${String(i+1).padStart(4,'0')}`,width:doc.width,height:doc.height,rgba:renderExportFrame(doc,f.id,options),durationMs:f.durationMs}));
 const atlas=options.atlas||packAtlas(entries,{...options,clips:doc.clips,slices:doc.slices,imageName:'sprites.png'}),files={'sprites.png':writePng(atlas.width,atlas.height,atlas.rgba),'sprites.json':json({frames:atlas.frames,meta:{...atlas.meta,image:'sprites.png',clips:doc.clips,slices:atlas.meta.slices||doc.slices,sourceSlices:doc.slices}}),[`${safe(projectDocument.name)}.pixelwall`]:json(projectDocument)},manifest={format:'pixelwall-game-package',version:1,frameScale:atlas.meta.scale||'1',tilemapScale:'1',project:`${safe(projectDocument.name)}.pixelwall`,atlas:{image:'sprites.png',metadata:'sprites.json'},frames:[],tilesets:[],maps:[],clips:doc.clips,slices:doc.slices,warnings:[]};
 for(const [index,entry]of entries.entries()){const path=`frames/${String(index+1).padStart(4,'0')}-${safe(entry.name||entry.id)}.png`;files[path]=writePng(entry.width,entry.height,entry.rgba);manifest.frames.push({frameId:entry.id||doc.frames[index]?.id,image:path,width:entry.width,height:entry.height,durationMs:entry.durationMs||entry.duration||100});}
 const palettes=[],framePalettes=new Map();let currentPalette=doc.palette;for(const frame of doc.frames){if(frame.palette)currentPalette=frame.palette;const key=doc.colorMode==='indexed'?JSON.stringify(currentPalette):'rgba';let index=palettes.findIndex(v=>v.key===key);if(index<0){index=palettes.length;palettes.push({key,palette:currentPalette});}framePalettes.set(frame.id,index);}
 const sets=new Map();let firstgid=1;
 for(const [tsi,ts]of (doc.tilesets||[]).entries()){
  const tiles=[];if(ts.tiles?.length){for(const tile of ts.tiles){const image=tileImage(doc,tile);tiles.push({sourceId:tile.id,asepriteTileId:tile.asepriteTileId,image,width:image.width,height:image.height});}}
  else if(ts.imageId){const image=doc.images[ts.imageId];assert(image&&!image.tilemap,'Embedded tileset image is missing.');const columns=Math.floor(image.width/ts.tileWidth),count=ts.tileCount??columns*Math.floor(image.height/ts.tileHeight);for(let index=0;index<count;index++){const sx=(index%columns)*ts.tileWidth,sy=Math.floor(index/columns)*ts.tileHeight,pixels=[];assert(sx+ts.tileWidth<=image.width&&sy+ts.tileHeight<=image.height,'Tileset dimensions exceed its atlas.');for(let y=0;y<ts.tileHeight;y++)for(let x=0;x<ts.tileWidth;x++)pixels.push(image.pixels[(sy+y)*image.width+sx+x]);tiles.push({sourceId:index,image:{width:ts.tileWidth,height:ts.tileHeight,pixels},width:ts.tileWidth,height:ts.tileHeight});}}
  else throw new Error(`Tileset “${ts.name}” has no embedded pixel data. Load its external source before exporting a game package.`);
  const localIds=new Map();tiles.forEach((tile,i)=>{localIds.set(tile.sourceId,i);if(Number.isInteger(tile.asepriteTileId))localIds.set(tile.asepriteTileId,i);});const info={firstgid,tiles,localIds,variants:[]};firstgid+=tiles.length;assert(firstgid<0x10000000,'Tiled global tile IDs exceed their supported range.');sets.set(ts.id,info);
  for(const [pi,variant]of palettes.entries()){
   const folder=`tilesets/${tsi+1}-${safe(ts.name)}${palettes.length>1?`-palette-${pi+1}`:''}`,path=`${folder}/tileset.tsj`,tileDefs=[];
   for(const [index,tile]of tiles.entries()){let palette=variant.palette;if(doc.colorMode==='indexed'&&Number.isInteger(doc.metadata?.aseprite?.transparentIndex)){palette=[...palette];palette[doc.metadata.aseprite.transparentIndex]='#00000000';}const imagePath=`tile-${String(index).padStart(4,'0')}.png`;files[`${folder}/${imagePath}`]=writePng(tile.width,tile.height,toExportRGBA(pixelsToRgba(tile.image.pixels,palette),doc,options));tileDefs.push({id:index,image:imagePath,imagewidth:tile.width,imageheight:tile.height,properties:[{name:'pixelwallTileId',type:'string',value:String(tile.sourceId)}]});}
   const tiled={type:'tileset',version:'1.10',name:ts.name,tilewidth:ts.tileWidth,tileheight:ts.tileHeight,tilecount:tiles.length,columns:0,margin:0,spacing:0,tiles:tileDefs,transformations:{hflip:true,vflip:true,rotate:true,preferuntransformed:true}};files[path]=json(tiled);files[`${folder}/pixelwall-tileset.json`]=json({...ts,exportedTiles:tileDefs.map(t=>({id:tiles[t.id].sourceId,image:`${folder}/${t.image}`}))});info.variants.push(path);manifest.tilesets.push({id:ts.id,name:ts.name,firstgid:info.firstgid,paletteIndex:pi,source:path,tileWidth:ts.tileWidth,tileHeight:ts.tileHeight,count:tiles.length});
  }
 }
 function transformGid(gid,cell){let fx=!!cell.flipX,fy=!!cell.flipY,diagonal=false;const rotation=((cell.rotate||0)%360+360)%360;assert([0,90,180,270].includes(rotation),'Tiled tiles require quarter-turn rotations.');if(rotation===90){diagonal=true;[fx,fy]=[!fy,fx];}if(rotation===180){fx=!fx;fy=!fy;}if(rotation===270){diagonal=true;[fx,fy]=[fy,!fx];}return(gid|(fx?0x80000000:0)|(fy?0x40000000:0)|(diagonal?0x20000000:0))>>>0;}

 const selectedFrameIds=new Set(entries.map(entry=>entry.id).filter(Boolean));
 for(const [fi,frame]of doc.frames.entries()){
  if(selectedFrameIds.size&&!selectedFrameIds.has(frame.id))continue;
  const groups=new Map();for(const layer of doc.layers){if(layer.type!=='tilemap')continue;const native=layer.tilemaps?.[frame.id],cel=frame.cels[layer.id],image=doc.images[cel?.imageId],ase=image?.tilemap,tilesetId=native?.tilesetId||layer.tilesetId;if(!native&&!ase)continue;const ts=doc.tilesets.find(t=>t.id===tilesetId),info=sets.get(tilesetId);assert(ts&&info,'Tilemap has no exported tileset.');const columns=native?.columns||image.width,rows=native?.rows||image.height,key=`${ts.tileWidth}x${ts.tileHeight}`;if(!groups.has(key))groups.set(key,{tilewidth:ts.tileWidth,tileheight:ts.tileHeight,layers:[],sets:new Set()});const group=groups.get(key),data=native?native.cells.map(cell=>{if(cell==null)return 0;const id=info.localIds.get(cell.tileId);assert(id!=null,'Tilemap refers to a missing tile.');return transformGid(info.firstgid+id,cell);}):ase.tiles.map(value=>{const raw=value>>>0,index=(raw&ase.idMask)>>>0;if((ts.flags&4)?index===0:raw===0xffffffff)return 0;const localId=info.localIds.get(index);assert(localId!=null,'Sprite tilemap refers to a missing tile.');let fx=!!(raw&ase.xFlipMask),fy=!!(raw&ase.yFlipMask);const diagonal=!!(raw&ase.diagonalFlipMask);return((info.firstgid+localId)|(fx?0x80000000:0)|(fy?0x40000000:0)|(diagonal?0x20000000:0))>>>0;});let opacity=(layer.opacity??1)*(native?(native.opacity??1):(cel.opacity??1)),visible=layer.visible!==false,parent=layer.parentId;while(parent){const ancestor=doc.layers.find(l=>l.id===parent);assert(ancestor,'Tilemap group parent is missing.');opacity*=ancestor.opacity??1;visible&&=ancestor.visible!==false;parent=ancestor.parentId;}
   if(ts.tileWidth!==ts.tileHeight&&data.some(gid=>gid&0x20000000))manifest.warnings.push('Some rotated rectangular tiles erase artwork beneath their empty areas. Tiled maps cannot preserve this effect. Use the included rendered frames or atlas for the exact appearance.');
   const mode=layer.blendMode==='addition'?'add':layer.blendMode||'normal';if(!['normal','add','multiply','screen','overlay','darken','lighten','color-dodge','color-burn','hard-light','soft-light','difference','exclusion'].includes(mode))manifest.warnings.push(`Tiled does not support the ${mode} blend mode on “${layer.name}”; the original setting is retained as a property and in the project.`);
   group.layers.push({type:'tilelayer',id:group.layers.length+1,name:layer.name,width:columns,height:rows,x:0,y:0,offsetx:native?native.x||0:cel.x,offsety:native?native.y||0:cel.y,opacity,visible,locked:!!layer.locked,mode:['normal','add','multiply','screen','overlay','darken','lighten','color-dodge','color-burn','hard-light','soft-light','difference','exclusion'].includes(mode)?mode:'normal',data,properties:[{name:'pixelwallLayerId',type:'string',value:layer.id},{name:'pixelwallParentId',type:'string',value:layer.parentId||''},{name:'pixelwallBlendMode',type:'string',value:layer.blendMode||'normal'}]});group.sets.add(tilesetId);
  }
  for(const [grid,group]of groups){const width=Math.max(Math.ceil(doc.width/group.tilewidth),...group.layers.map(l=>l.width)),height=Math.max(Math.ceil(doc.height/group.tileheight),...group.layers.map(l=>l.height));for(const layer of group.layers){if(layer.width!==width||layer.height!==height){const data=new Array(width*height).fill(0);for(let y=0;y<layer.height;y++)for(let x=0;x<layer.width;x++)data[y*width+x]=layer.data[y*layer.width+x];layer.width=width;layer.height=height;layer.data=data;}}
   const path=`maps/frame-${String(fi+1).padStart(4,'0')}-${grid}.tmj`,map={type:'map',version:'1.10',orientation:'orthogonal',renderorder:'right-down',infinite:false,width,height,tilewidth:group.tilewidth,tileheight:group.tileheight,nextlayerid:group.layers.length+1,nextobjectid:1,layers:group.layers,tilesets:[...sets.keys()].map(id=>{const info=sets.get(id);return{firstgid:info.firstgid,source:`../${info.variants[framePalettes.get(frame.id)]}`};}),properties:[{name:'pixelwallFrameId',type:'string',value:frame.id},{name:'durationMs',type:'int',value:frame.durationMs}]};files[path]=json(map);manifest.maps.push({frameId:frame.id,durationMs:frame.durationMs,grid,source:path});
  }
 }
 if(manifest.maps.length&&!isSRGB(documentProfile(doc)))manifest.warnings.push('Tile images are converted to sRGB. A Tiled renderer composites them in its own color space, so overlapping translucent tiles or blend modes can differ from the original profile. Use the rendered frames or atlas for the exact composite.');
 if(manifest.maps.length&&doc.layers.some(l=>l.type!=='tilemap'))manifest.warnings.push('Tiled maps contain the tilemap layers. Rendered frame PNGs and the native project retain all raster and group artwork.');manifest.warnings=[...new Set(manifest.warnings)];files['manifest.json']=json(manifest);return zipSync(files);
}
